import test from 'node:test';import assert from 'node:assert/strict';
import {voltageDrop,adiabaticCheck,ampacityCheck,conduitFill,effectiveProperty,coerceProperty,validateProperties,propertyDefinitions} from '../packages/engineering/index.js';
import {createProject,createEntity,symbols} from '../packages/core/index.js';
import {createCabinet,addComponent,routeCabinet,cabinetIssues,mountingDXF,cutList} from '../packages/cabinet/index.js';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} ≠ ${b}`);
test('voltage drop independent DC and balanced three-phase fixtures',()=>{near(voltageDrop({system:'dc',voltage:24,current:10,lengthM:30,sectionMM2:2.5,resistanceOhmKM:7.41}).dropV,4.446);near(voltageDrop({voltage:400,current:32,lengthM:50,sectionMM2:10,resistanceOhmKM:1.83,powerFactor:.8,reactanceOhmKM:.08}).dropV,4.190177313670628);near(voltageDrop({voltage:400,current:32,lengthM:50,sectionMM2:10,resistanceOhmKM:1.83,temperatureC:70}).resistanceOhmKM,2.189595);});
test('adiabatic withstand and correction-factor fixtures',()=>{const a=adiabaticCheck({faultCurrentA:1000,clearingTimeS:.1,k:115,sectionMM2:4});near(a.requiredSectionMM2,Math.sqrt(100000)/115);assert.equal(a.withstandI2t,211600);const b=ampacityCheck({referenceAmpacityA:20,ambientFactor:.87,groupingFactor:.8,loadCurrentA:10,protectiveRatingA:13,conventionalTripA:18.85});near(b.correctedAmpacityA,13.92);assert.equal(b.passes,true);assert.equal(ampacityCheck({...b.inputs,conventionalTripA:undefined}).passes,null);assert.equal(ampacityCheck({...b.inputs,conventionalTripA:30}).passes,false);});
test('duct fill rejects physically impossible inputs',()=>{near(conduitFill({widthMM:20,heightMM:30,wires:[{diameterMM:3,quantity:10}]}).fillPercent,11.78097245096);assert.throws(()=>conduitFill({widthMM:10,heightMM:10,wires:[{diameterMM:15}]}));assert.throws(()=>conduitFill({widthMM:10,heightMM:10,limitPercent:200}));assert.throws(()=>conduitFill({widthMM:10,heightMM:10,wires:[{diameterMM:2,quantity:.5}]}));});
test('typed properties reject typos and inherit main-function parts',()=>{const p=createProject();const main=createEntity(p,'coil',0,0,{tag:'-K1',part:'P1',isMain:true});const aux=createEntity(p,'contact_no',0,0,{tag:'-K1',part:'',isMain:false});p.pages[0].entities=[main,aux];p.parts=[{id:'part1',part:'P1',manufacturer:'Vendor'}];assert.equal(effectiveProperty(p,aux,'manufacturer').value,'Vendor');assert.throws(()=>coerceProperty('isMain','tru'));assert.throws(()=>coerceProperty('powerFactor',1.1));assert.ok(propertyDefinitions.size>=50);assert.equal(validateProperties(p).length,0);});
test('all symbols have finite transformed pins and vector primitives',()=>{const defs=[...symbols.values()];assert.ok(defs.length>=75);for(const s of defs){assert.ok(s.id);assert.ok(s.pins);assert.ok(s.primitives?.length||s.shapes?.length);} });
test('3D route avoids a blocking volume and ignores an unrelated tall part',()=>{const c={...createCabinet(),width:400,height:300,depth:250};const a=addComponent(c,{x:20,y:20,z:0,width:40,height:40,depth:20}),b=addComponent(c,{x:300,y:20,z:0,width:40,height:40,depth:20});addComponent(c,{x:160,y:0,z:0,width:40,height:100,depth:100});addComponent(c,{x:300,y:220,z:0,width:40,height:40,depth:240});const r=routeCabinet(c,{source:a.id,target:b.id});c.routes=[r];assert.ok(r.lengthMM>260);assert.equal(cabinetIssues(c).filter(i=>i.device===r.id).length,0);assert.ok(cutList(c)[0].cutMM>=r.lengthMM);assert.ok(mountingDXF(c).endsWith('EOF'));});
test('layout checking includes cable radius and rejects missing endpoints',()=>{const c=createCabinet();addComponent(c,{x:10,y:10,z:10,width:10,height:10,depth:10});c.routes=[{id:'route',source:'a',target:'b',diameter:10,clearance:0,points:[{x:0,y:8,z:15},{x:30,y:8,z:15}]}];assert.ok(cabinetIssues(c).some(i=>i.message.includes('intersects')));assert.ok(cabinetIssues(c).some(i=>i.message.includes('endpoint')));});

test('project networks join feedthroughs and matching interruption points across pages',async()=>{const {projectNetworks}=await import('../packages/engineering/networks.js');const {createPage,createWire}=await import('../packages/core/index.js');const p=createProject(),a=p.pages[0];const e=createEntity(p,'terminal',100,100,{tag:'-X1',terminal:'1',interruptionPoint:'A'});a.entities=[e];a.wires=[createWire([{x:100,y:80},{x:100,y:0}]),createWire([{x:100,y:120},{x:100,y:180}])];const b=createPage();b.entities=[createEntity(p,'terminal',100,100,{tag:'-X2',terminal:'1',interruptionPoint:'A'})];p.pages.push(b);const nets=projectNetworks(p);assert.equal(nets.length,1);assert.equal(nets[0].pages.length,2);});
test('moved cabinet endpoints invalidate cut instructions',()=>{const c=createCabinet(),a=addComponent(c,{x:20,y:20}),b=addComponent(c,{x:300,y:20});c.routes=[routeCabinet(c,{source:a.id,target:b.id})];assert.ok(cutList(c)[0].cutMM>0);a.x+=20;assert.equal(cutList(c)[0].cutMM,'');});
