import test from 'node:test';import assert from 'node:assert/strict';
import {createProject,createPage,createEntity,clone} from '../packages/core/index.js';import {diffProject,applyChanges,mergeOperationProjects} from '../packages/collaboration/operations.js';
import {createDatabase} from '../server/sqlite.js';import {api} from '../server/api.js';import {operationStream} from '../server/operations.js';import {LiveCollaborationClient} from '../packages/collaboration/live.js';
const db=createDatabase(),env={DB:db};async function request(path,method='GET',body){const res=await api(new Request('https://test.invalid/api'+path,{method,headers:{'oai-authenticated-user-id':'owner','Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})}),env);return {status:res.status,data:await res.json()};}
async function setup(){const p=createProject();p.pages[0].entities=[createEntity(p,'coil',20,20)];await request('/projects','POST',{project:p});return p;}
const packet=(a,b,revision=1,id=crypto.randomUUID())=>({operationId:id,baseRevision:revision,changes:diffProject(a,b)});
test('field operations merge separate properties on the same device',()=>{const b=createProject();b.pages[0].entities=[createEntity(b,'coil',20,20)];const l=clone(b),r=clone(b);l.pages[0].entities[0].x=100;r.pages[0].entities[0].label='Remote';const m=mergeOperationProjects(b,l,r);assert.equal(m.conflicts.length,0);assert.equal(m.project.pages[0].entities[0].x,100);assert.equal(m.project.pages[0].entities[0].label,'Remote');r.pages[0].entities[0].x=200;assert.equal(mergeOperationProjects(b,l,r).conflicts.length,1);});
test('page reordering survives operation round trip',()=>{const p=createProject();p.pages.push(createPage());const q=clone(p);q.pages.reverse();assert.deepEqual(applyChanges(p,diffProject(p,q)).project.pages.map(p=>p.id),q.pages.map(p=>p.id));});
test('server operations are idempotent, journaled and preserve concurrent fields',async()=>{const p=await setup(),a=clone(p),b=clone(p);a.pages[0].entities[0].x=100;b.pages[0].entities[0].label='Remote';const pa=packet(p,a),pb=packet(p,b);const responses=await Promise.all([request('/projects/'+p.id+'/operations','POST',pa),request('/projects/'+p.id+'/operations','POST',pb)]);assert.deepEqual(responses.map(r=>r.status),[200,200]);const again=await request('/projects/'+p.id+'/operations','POST',pa);assert.equal(again.data.revision,3);assert.equal(again.data.duplicate,true);assert.equal(again.data.project.pages[0].entities[0].label,'Remote');assert.equal((await request('/projects/'+p.id+'/journal')).data.length,2);assert.equal((await request('/projects/'+p.id+'/history')).data.length,3);const corrupt={...pa,baseRevision:99};assert.equal((await request('/projects/'+p.id+'/operations','POST',corrupt)).status,409);});
test('global tombstones reject whole-array and legacy PUT resurrection',async()=>{const p=await setup(),deleted=clone(p);deleted.pages[0].entities=[];assert.equal((await request('/projects/'+p.id+'/operations','POST',packet(p,deleted))).status,200);const bulk={operationId:crypto.randomUUID(),baseRevision:2,changes:[{path:['pages',{id:p.pages[0].id},'entities'],before:{exists:true,value:[]},after:{exists:true,value:p.pages[0].entities}}]};assert.equal((await request('/projects/'+p.id+'/operations','POST',bulk)).status,409);assert.equal((await request('/projects/'+p.id,'PUT',{project:p,revision:2})).status,409);});
test('SSE emits revisions, presence and closes after its bounded stream window',async()=>{const p=await setup();const response=operationStream(db,{projectId:p.id,user:'owner',name:'Engineer',since:0,intervalMS:1,maxTicks:2});const body=await response.text();assert.match(body,/event: ready/);assert.match(body,/event: revision/);assert.match(body,/event: presence/);assert.match(body,/event: reconnect/);});
test('recovery replays lost receipt before rebasing later edits',async()=>{const data=new Map();globalThis.localStorage={getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};const p=createProject(),sent=clone(p),remote=clone(p);sent.name='Committed';remote.name='Later collaborator';const op=packet(p,sent);data.set('relayforge-operation-outbox:owner:'+p.id,JSON.stringify({base:p,pending:sent,packet:op,packetProject:sent,revision:1}));let replays=0,conflicts=0,result;const client=new LiveCollaborationClient({onRemote:p=>result=p,onConflict:()=>conflicts++});client.request=async(path)=>path==='/me'?{id:'owner'}:path.endsWith('/operations')?(replays++,{project:remote,revision:3,duplicate:true}):{project:remote,revision:3,role:'owner'};await client.open(p.id);await client.save();assert.equal(replays,1);assert.equal(conflicts,0);assert.equal(result.name,'Later collaborator');client.dispose();delete globalThis.localStorage;});

test('undo of a committed deletion restores a fresh identity that can synchronize',async()=>{const {ProjectStore}=await import('../packages/core/index.js');const p=await setup(),store=new ProjectStore(p),oldId=p.pages[0].entities[0].id;store.transact('Delete',p=>p.pages[0].entities=[]);const removed=clone(store.project);await request('/projects/'+p.id+'/operations','POST',packet(p,removed));store.undo();assert.notEqual(store.project.pages[0].entities[0].id,oldId);assert.equal((await request('/projects/'+p.id+'/operations','POST',packet(removed,store.project,2))).status,200);});
