import test from 'node:test';import assert from 'node:assert/strict';import {createDatabase} from '../server/sqlite.js';import {api} from '../server/api.js';import {createProject} from '../packages/core/index.js';
const db=createDatabase();const env={DB:db};const p=createProject('Integration project');
async function request(path,method='GET',data,user='owner'){const req=new Request('https://example.test/api'+path,{method,headers:{'Content-Type':'application/json',...(user?{'oai-authenticated-user-id':user,'oai-authenticated-user-email':user+'@example.test'}:{})},...(data?{body:JSON.stringify(data)}:{})});const response=await api(req,env);return {status:response.status,data:await response.json()};}
test('authentication is required',async()=>{assert.equal((await request('/projects','GET',null,null)).status,401);});
test('create, revision checks, history, membership and comments',async()=>{let r=await request('/projects','POST',{project:p});assert.equal(r.status,201);assert.equal(r.data.revision,1);assert.equal((await request('/projects/'+p.id,'GET',null,'stranger')).status,404);
p.name='Updated';r=await request('/projects/'+p.id,'PUT',{project:p,revision:1});assert.equal(r.status,200);assert.equal(r.data.revision,2);
r=await request('/projects/'+p.id,'PUT',{project:p,revision:1});assert.equal(r.status,409);assert.equal(r.data.project.name,'Updated');assert.equal((await request('/projects/'+p.id+'/history')).data.length,2);
r=await request('/projects/'+p.id+'/invite','POST',{role:'viewer'});const token=r.data.token;assert.ok(token);r=await request('/join','POST',{token},'viewer');assert.equal(r.status,200);assert.equal((await request('/projects/'+p.id,'PUT',{project:p,revision:2},'viewer')).status,403);assert.equal((await request('/projects/'+p.id,'GET',null,'viewer')).data.role,'viewer');
r=await request('/projects/'+p.id+'/comments','POST',{text:'Check supply',pageId:p.pages[0].id});assert.equal(r.status,200);const comment=(await request('/projects/'+p.id+'/comments')).data[0];assert.equal(comment.text,'Check supply');assert.equal((await request('/projects/'+p.id+'/comments','PATCH',{id:comment.id,resolved:true})).status,200);assert.equal((await request('/projects/'+p.id+'/comments')).data[0].resolved,1);
r=await request('/projects/'+p.id+'?since=2');assert.equal(r.data.unchanged,true);assert.equal(r.data.presence.length,2);});
test('cross-origin mutation is refused',async()=>{const r=await api(new Request('https://example.test/api/projects',{method:'POST',headers:{'oai-authenticated-user-id':'owner','origin':'https://attacker.test'},body:'{}'}),env);assert.equal(r.status,403);});
test('invalid invitation cannot grant access',async()=>{assert.equal((await request('/join','POST',{token:'wrong'},'attacker')).status,404);});
test('removing a member invalidates reusable invitation links',async()=>{let r=await request('/projects/'+p.id+'/invite','POST',{role:'editor'});const token=r.data.token;await request('/join','POST',{token},'member-to-remove');assert.equal((await request('/projects/'+p.id,'GET',null,'member-to-remove')).status,200);await request('/projects/'+p.id+'/members','DELETE',{userId:'member-to-remove'});assert.equal((await request('/join','POST',{token},'member-to-remove')).status,404);assert.equal((await request('/projects/'+p.id,'GET',null,'member-to-remove')).status,404);});
