import {uid} from '../core/index.js';
import {xmlEscape as x,parseXML,descendants,child,nodeText} from './xml.js';
export const INTERCHANGE_VERSION='0.2.0';
export const plcTypes=['BOOL','BYTE','WORD','DWORD','INT','DINT','REAL','LREAL','STRING'];
export function normalizeTags(tags){const seen=new Set();return tags.map(t=>{const name=String(t.name||'').trim();if(!/^[A-Za-z_][A-Za-z0-9_]*$/.test(name))throw Error('PLC variable names must be IEC identifiers: '+name);const scope=String(t.scope||'Main');const key=scope+':'+name;if(seen.has(key))throw Error('Duplicate PLC variable '+key);seen.add(key);const dataType=String(t.dataType||'BOOL').toUpperCase();if(!plcTypes.includes(dataType))throw Error('Unsupported PLC data type '+dataType);return {id:t.id||uid(),name,scope,dataType,address:String(t.address||''),description:String(t.description||''),ioType:t.ioType||(/^[%]?I/.test(t.address||'')?'Input':/^[%]?Q/.test(t.address||'')?'Output':'Memory'),alias:String(t.alias||'')};});}
export function projectTags(project){if(project.plc?.tags?.length)return normalizeTags(project.plc.tags);return normalizeTags(project.pages.flatMap(p=>p.entities.filter(e=>e.symbol.startsWith('plc')).flatMap(e=>(e.channels||[{address:e.plcAddress||'I0.0',name:e.plcSymbol||e.tag.replace(/[^a-z0-9_]/gi,'')+'_Input',dataType:e.dataType||'BOOL'}]).map(c=>({...c,name:c.name||'Tag_'+uid().slice(0,8),description:c.description||e.label,scope:e.cpu||'Main'})))));}
function iecAddress(address){if(!address)return '';if(address[0]==='%')return address;if(/^[IQM]\d+\.\d+$/.test(address))return '%'+address[0]+'X'+address.slice(1);return address;}
export function exportPLCopen(project,tags=projectTags(project)){tags=normalizeTags(tags);const groups=Map.groupBy(tags,t=>t.scope);if(!groups.size)groups.set('Main',[]);const pous=[...groups].map(([scope,items])=>{if(!/^[A-Za-z_][A-Za-z0-9_]*$/.test(scope))throw Error('PLCopen POU scope must be an IEC identifier');return `<pou name="${x(scope)}" pouType="program"><interface><localVars>${items.map(t=>`<variable name="${x(t.name)}"${t.address?` address="${x(iecAddress(t.address))}"`:''}><type><${t.dataType==='STRING'?'string':t.dataType}/></type>${t.description?`<documentation><xhtml:p>${x(t.description)}</xhtml:p></documentation>`:''}</variable>`).join('')}</localVars></interface><body><ST><xhtml:p>(* Variable exchange only. No control logic generated. *)</xhtml:p></ST></body></pou>`;}).join('');return `<?xml version="1.0" encoding="UTF-8"?><project xmlns="http://www.plcopen.org/xml/tc6_0201" xmlns:xhtml="http://www.w3.org/1999/xhtml"><fileHeader companyName="RelayForge" productName="RelayForge Electrical" productVersion="0.2.0" creationDateTime="${new Date().toISOString()}"/><contentHeader name="${x(project.name)}"><coordinateInfo><fbd><scaling x="1" y="1"/></fbd><ld><scaling x="1" y="1"/></ld><sfc><scaling x="1" y="1"/></sfc></coordinateInfo></contentHeader><types><dataTypes/><pous>${pous}</pous></types><instances><configurations/></instances></project>`;}
export function importPLCopen(source){const root=parseXML(source);if(root.localName!=='project'||root.namespaceURI!=='http://www.plcopen.org/xml/tc6_0201')throw Error('Expected PLCopen XML 2.01');const mapped=new Set(),tags=[];for(const pou of descendants(root,'pou'))for(const v of descendants(child(pou,'interface'),'variable')){const type=child(v,'type')?.children[0];if(!type)throw Error('Variable has no type');mapped.add(v);tags.push({name:v.attributes.name,address:v.attributes.address||'',dataType:type.localName.toUpperCase(),description:nodeText(child(v,'documentation')),scope:pou.attributes.name});}if(descendants(root,'globalVars').length)throw Error('This adapter supports POU variables only; configuration globals and structured variables require explicit conversion');return {format:'PLCopen 2.01 variables',tags:normalizeTags(tags),source,notes:['POU scopes preserved. Program bodies and vendor extensions retained as original source only.']};}
export function parseCSV(source){if(source.length>2_000_000)throw Error('CSV too large');const rows=[],row=[];let value='',quoted=false;for(let i=0;i<source.length;i++){const c=source[i];if(c==='"'){if(quoted&&source[i+1]==='"'){value+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(value);value='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&source[i+1]==='\n')i++;row.push(value);if(row.some(Boolean))rows.push(row.splice(0));else row.length=0;value='';}else value+=c;}if(quoted)throw Error('Unterminated CSV quote');row.push(value);if(row.some(Boolean))rows.push(row);return rows;}
const csvCell=v=>'"'+String(v??'').replaceAll('"','""')+'"';
const logixEncode=s=>String(s).replaceAll('$',()=> '$$').replaceAll('"','$Q').replace(/\r?\n/g,'$N$L').replaceAll('\t','$T');
const logixDecode=s=>s.replace(/\$(\$|Q|N\$L|T)/g,(_,v)=>({'$':'$',Q:'"','N$L':'\n',T:'\t'}[v]));
export function exportRockwellCSV(tags){return [['TYPE','SCOPE','NAME','DESCRIPTION','DATATYPE','SPECIFIER','ATTRIBUTES'],...logixTags(tags).map(t=>[t.alias?'ALIAS':'TAG',t.scope==='Controller'?'':t.scope,t.name,logixEncode(t.description),t.alias?'':t.dataType,t.alias||'', '(RADIX := Decimal, Constant := false, ExternalAccess := Read/Write)'])].map(r=>r.map(csvCell).join(',')).join('\r\n');}
export function importRockwellCSV(source){const rows=parseCSV(source);const headerIndex=rows.findIndex(r=>r[0].toUpperCase()==='TYPE'&&r.some(s=>s.toUpperCase()==='NAME'));if(headerIndex<0)throw Error('Rockwell TAG/ALIAS CSV header missing');const header=rows[headerIndex].map(x=>x.toUpperCase());const tags=rows.slice(headerIndex+1).filter(r=>['TAG','ALIAS'].includes(r[0].toUpperCase())).map(r=>{const get=k=>r[header.indexOf(k)]||'';return {name:get('NAME'),scope:get('SCOPE')||'Controller',description:logixDecode(get('DESCRIPTION')),dataType:get('DATATYPE')||'BOOL',address:'',alias:get('TYPE')==='ALIAS'?get('SPECIFIER'):''};});return {format:'Rockwell TAG/ALIAS CSV',tags:logixTags(tags),source,notes:['Hardware addresses are not encoded as tag addresses in this Rockwell format.']};}
const logixTypes=['BOOL','INT','DINT','REAL'];
function logixTags(tags){return normalizeTags(tags).map(t=>{if(!t.alias&&!logixTypes.includes(t.dataType))throw Error('Logix scalar adapter does not support '+t.dataType+'; no implicit signedness or structure conversion is performed');return t;});}
export function exportL5X(project,tags=projectTags(project)){const groups=Map.groupBy(logixTags(tags),t=>t.scope);const render=items=>`<Tags>${items.map(t=>`<Tag Name="${x(t.name)}" TagType="${t.alias?'Alias':'Base'}"${t.alias?` AliasFor="${x(t.alias)}"`:` DataType="${x(t.dataType)}" Radix="Decimal" Constant="false" ExternalAccess="Read/Write"`}><Description>${x(t.description)}</Description>${t.alias?'':'<Data Format="L5K"><![CDATA[0]]></Data>'}</Tag>`).join('')}</Tags>`;return `<?xml version="1.0" encoding="UTF-8"?><RSLogix5000Content SchemaRevision="1.0" SoftwareRevision="35.00" TargetName="RelayForgeTags" TargetType="Controller" ContainsContext="true" Owner="RelayForge" ExportDate="${new Date().toISOString()}" ExportOptions="References NoRawData L5KData Context Dependencies"><Controller Name="RelayForgeTags" Use="Context">${render(groups.get('Controller')||[])}<Programs>${[...groups].filter(([s])=>s!=='Controller').map(([scope,items])=>`<Program Name="${x(scope)}" Use="Context">${render(items)}</Program>`).join('')}</Programs></Controller></RSLogix5000Content>`;}
export function importL5X(source){const root=parseXML(source);if(root.localName!=='RSLogix5000Content')throw Error('Expected Logix L5X content');const controller=child(root,'Controller');if(!controller)throw Error('L5X Controller context missing');const tags=[];const read=(container,scope)=>{for(const t of child(container,'Tags')?.children||[])if(t.localName==='Tag'){if(t.attributes.Dimensions)throw Error('Logix arrays require explicit conversion');tags.push({name:t.attributes.Name,scope,dataType:t.attributes.DataType||'BOOL',description:nodeText(child(t,'Description')),alias:t.attributes.AliasFor||''});}};read(controller,'Controller');for(const p of child(controller,'Programs')?.children||[])if(p.localName==='Program')read(p,p.attributes.Name);return {format:'Rockwell L5X tag subset',tags:logixTags(tags),source,notes:['Controller and program scopes preserved. BOOL/INT/DINT/REAL and aliases only. Initial values, routines, modules and safety signatures are not mapped.']};}
const attr=(name,value)=>`<Attribute Name="${x(name)}" AttributeDataType="xs:string"><Value>${x(value)}</Value></Attribute>`;
export function exportAutomationML(project,tags=projectTags(project)){return `<?xml version="1.0" encoding="UTF-8"?><CAEXFile FileName="${x(project.number||'project')}.aml" SchemaVersion="2.15" xmlns:xs="http://www.w3.org/2001/XMLSchema"><AdditionalInformation><WriterHeader><WriterName>RelayForge Electrical</WriterName><WriterVersion>0.2.0</WriterVersion></WriterHeader></AdditionalInformation><InstanceHierarchy Name="${x(project.name)}"><InternalElement Name="AutomationProject" ID="${uid()}"><SupportedRoleClass RefRoleClassPath="AutomationProjectConfigurationRoleClassLib/AutomationProject"/><InternalElement Name="Tags" ID="${uid()}"><SupportedRoleClass RefRoleClassPath="AutomationProjectConfigurationRoleClassLib/TagTable"/>${normalizeTags(tags).map(t=>`<ExternalInterface Name="${x(t.name)}" ID="${x(t.id)}" RefBaseClassPath="AutomationProjectConfigurationInterfaceClassLib/Tag">${attr('DataType',t.dataType)}${attr('IoType',t.ioType)}${attr('LogicalAddress',t.address)}${attr('Comment',t.description)}${attr('Scope',t.scope)}</ExternalInterface>`).join('')}</InternalElement></InternalElement></InstanceHierarchy></CAEXFile>`;}
export function importAutomationML(source){const root=parseXML(source);if(root.localName!=='CAEXFile'||root.attributes.SchemaVersion!=='2.15')throw Error('Expected AutomationML CAEX 2.15');const tags=descendants(root,'ExternalInterface').filter(e=>e.attributes.RefBaseClassPath==='AutomationProjectConfigurationInterfaceClassLib/Tag').map(e=>{const attrs=Object.fromEntries(e.children.filter(a=>a.localName==='Attribute').map(a=>[a.attributes.Name,nodeText(child(a,'Value'))]));return {id:e.attributes.ID,name:e.attributes.Name,dataType:attrs.DataType||'BOOL',address:attrs.LogicalAddress||'',ioType:attrs.IoType||'Memory',description:attrs.Comment||'',scope:attrs.Scope||'Main'};});return {format:'AutomationML APC tag subset',tags:normalizeTags(tags),source,notes:['APC tag interfaces are mapped. CAEX source and unknown device/network structures are retained for inspection. Target vendor acceptance requires matching profile/version qualification.']};}
export function importPLC(source,filename){if(/\.csv$/i.test(filename))return importRockwellCSV(source);const root=parseXML(source);if(root.localName==='project')return importPLCopen(source);if(root.localName==='CAEXFile')return importAutomationML(source);if(root.localName==='RSLogix5000Content')return importL5X(source);throw Error('Unsupported PLC interchange format');}
