import {renewRestoredIdentities,ProjectStore,createProject,createPage,createEntity,createWire,clone,uid,snap,getSymbol,symbols,getPins,hitTest,validateProject,validateElectrical,numberWires,bomReport,connectionsReport,terminalReport,plcReport,crossReferences,toCSV,nextTag} from '../packages/core/index.js';
import {SchematicRenderer,exportSVG} from '../packages/renderer/index.js';
import {defineControls,icon,escapeHTML as h} from '../packages/controls/index.js';
import {createCollaborationClient, browserLocal, preferences} from './storage.js';
import {installAdvanced} from './advanced.js';
import {demoProject} from './demo.js';
defineControls();
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let store=new ProjectStore(demoProject()),pageId=store.project.pages[1].id,selected=new Set(),activeTab='Home',nav='pages',bottom='messages',tool='select',placeSymbol='breaker',snapping=true,clipboard=null,drag=null,wirePoints=[],space=false,suppress=false,issues=[],activity=[],comments=[],user={name:'Engineer',id:''},dirty=false,ready=false,editingAllowed=true;
const renderer=new SchematicRenderer($('#viewport'));
const page=()=>store.project.pages.find(p=>p.id===pageId)||store.project.pages[0];
const client=createCollaborationClient({onRemote:p=>{suppress=true;store.replace(p);suppress=false;toast('Project updated from shared revision');},onConflict:showConflict});
let toastTimer;
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4200);}
function act(label,fn){if(!editingAllowed){toast('You have view-only access to this project.');return;}try{store.transact(label,fn);}catch(e){toast(e.message);}}
function download(name,content,type='application/json'){const u=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function safeName(s){return s.replace(/[^a-z0-9_-]/gi,'-');}
function btn(action,label,ic,extra=''){return `<button data-action="${action}" ${extra}>${ic?icon(ic):''}${label}</button>`;}
const catalog={
 Home:[['Clipboard',[['copy','Copy','copy'],['paste','Paste','page'],['duplicate','Duplicate','copy']]],['Edit',[['select','Select','select'],['wire','Connection','wire'],['rotate','Rotate','rotate'],['delete','Delete','trash']]],['Insert',[['symbols','Symbol','bolt'],['text','Text','text'],['newPage','New page','page']]],['Engineering',[['number','Number wires','number'],['validate','Check project','check'],['reports','Generate reports','report']]],['Navigate',[['fit','Fit page','fit'],['findDevice','Find device','search']]]],
 Insert:[['Objects',[['symbols','Symbol library','bolt'],['wire','Connection','wire'],['text','Text','text'],['junction','Junction','plus']]],['Pages',[['newPage','New page','page'],['duplicatePage','Duplicate page','copy']]],['Reusable circuits',[['saveMacro','Save macro','save'],['macros','Insert macro','layers']]],['Import',[['import','Project JSON','upload']]]],
 Project:[['Project',[['projects','Open project','folder'],['newProject','New project','plus'],['save','Save','save'],['projectSettings','Properties','settings']]],['Pages',[['newPage','New page','page'],['pageSettings','Page properties','settings'],['duplicatePage','Duplicate page','copy'],['deletePage','Delete page','trash']]],['Revision',[['history','Revision history','history'],['collaborate','Collaborate','users']]]],
 Devices:[['Navigation',[['deviceNav','Devices','chip'],['findDevice','Find device','search'],['symbols','Symbols','bolt']]],['Device tools',[['rotate','Rotate','rotate'],['duplicate','Duplicate','copy'],['align','Align left','list']]],['Engineering data',[['parts','Parts list','report'],['terminals','Terminal strips','terminal'],['plc','PLC addresses','chip']]]],
 Connections:[['Draw',[['wire','Connection','wire'],['junction','Junction','plus'],['potential','Potential','bolt']]],['Connections',[['number','Number wires','number'],['connections','Connection list','list'],['terminals','Terminal strips','terminal']]],['Check',[['validate','Check project','check'],['pins','Show pins','plus']]]],
 Reports:[['Engineering reports',[['parts','Parts list','report'],['connections','Connections','wire'],['terminals','Terminals','terminal'],['plc','PLC I/O','chip'],['devicesReport','Device list','list']]],['Output',[['exportSVG','Export SVG','download'],['print','Print / PDF','print'],['export','Project JSON','download']]]],
 View:[['Drawing',[['fit','Fit page','fit'],['zoomIn','Zoom in','zoom'],['zoomOut','Zoom out','search'],['grid','Grid','grid'],['snap','Snap','plus'],['pins','Pins','plus']]],['Workspace',[['toggleNavigator','Navigator','list'],['toggleProperties','Properties','settings'],['toggleBottom','Messages','report'],['theme','Theme','moon']]],['Information',[['help','Shortcuts','help'],['about','About','bolt']]]]
};
const actions={};
function renderRibbon(){const tabs=['File',...Object.keys(catalog)];$('#ribbon-tabs').innerHTML=tabs.map(t=>`<button data-tab="${t}" class="${activeTab===t?'active':''}">${t}</button>`).join('');$('#ribbon').innerHTML=(catalog[activeTab]||catalog.Home).map(([label,items])=>`<div class="ribbon-group"><div class="ribbon-group-content">${items.map(([action,title,ic])=>`<button class="ribbon-button ${['symbols','wire','validate'].includes(action)?'primary':''} ${tool===action?'active':''}" data-action="${action}" title="${title}">${icon(ic,24)}<span>${title}</span></button>`).join('')}</div><div class="ribbon-group-label">${label}</div></div>`).join('');}
function renderNavigator(){const filter=$('#nav-filter').value.toLowerCase();$('#project-root').innerHTML=icon('down',13)+icon('folder',16)+`<span>${h(store.project.name)}</span>`;$$('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===nav));if(nav==='symbols'){const defs=[...symbols.values()].filter(s=>s.name.toLowerCase().includes(filter));$('#nav-content').innerHTML=[...new Set(defs.map(s=>s.category))].map(c=>`<div class="symbol-category">${h(c)}</div><div class="symbol-grid">${defs.filter(s=>s.category===c).map(s=>`<button class="symbol-card ${tool==='place'&&placeSymbol===s.id?'active':''}" data-symbol="${s.id}">${symbolThumbnail(s)}<span>${h(s.name)}</span></button>`).join('')}</div>`).join('');return;}
$('#nav-content').innerHTML='<rf-tree></rf-tree>';const tree=$('rf-tree');tree.data=nav==='pages'?store.project.pages.map((p,i)=>({id:p.id,label:`${String(i+1).padStart(3,'0')}   ${p.name}`,icon:p.type==='cover'?'page':p.type==='layout'?'layers':'wire',depth:1})).filter(x=>x.label.toLowerCase().includes(filter)):store.project.pages.flatMap((p,i)=>p.entities.map(e=>({id:e.id,label:e.tag+'  '+(e.label||getSymbol(e.symbol).name),icon:e.symbol==='terminal'?'terminal':'chip',meta:String(i+1),depth:1}))).filter(x=>x.label.toLowerCase().includes(filter));tree.selected=nav==='pages'?pageId:[...selected][0];tree.onitemselect=e=>{if(nav==='pages')openPage(e.detail.id);else goToEntity(e.detail.id);};}
function symbolThumbnail(s){const shapes=s.shapes.map(a=>{if(a.kind==='polyline')return `<polyline points="${a.points.reduce((r,x,i)=>r+(i%2?',':' ')+x,'')}"/>`;if(a.kind==='rect')return `<rect x="${a.x}" y="${a.y}" width="${a.w}" height="${a.h}"/>`;if(a.kind==='circle')return `<circle cx="${a.x}" cy="${a.y}" r="${a.r}"/>`;return `<text x="${a.x}" y="${a.y}" font-size="${a.size}" text-anchor="middle" stroke="none" fill="currentColor">${h(a.value)}</text>`;}).join('');return `<svg viewBox="-60 -80 120 160" fill="none" stroke="currentColor" stroke-width="2.5">${shapes}</svg>`;}
function renderTabs(){const current=page();$('#document-tabs').innerHTML=store.project.pages.map((p,i)=>`<button class="document-tab ${current.id===p.id?'active':''}" data-page="${p.id}" title="${h(p.name)}">${icon(p.type==='layout'?'layers':'page',14)}<span>${String(i+1).padStart(3,'0')} ${h(p.name)}</span></button>`).join('');$('#breadcrumbs').innerHTML=`<span>${h(current.structure)}</span>${icon('chevron',10)}<b>${h(current.name)}</b>`;$('#page-status').textContent=`Page ${store.project.pages.indexOf(current)+1} / ${store.project.pages.length}`;}
function renderInspector(){const p=page(),entity=p.entities.find(e=>selected.has(e.id)),wire=p.wires.find(e=>selected.has(e.id)),annotation=p.annotations.find(e=>selected.has(e.id)),item=entity||wire||annotation;let fields,values,title,subtitle,ic;
if(entity){title=entity.tag;subtitle=getSymbol(entity.symbol).name;ic='chip';values=entity;fields=[{key:'tag',label:'Device tag'},{key:'label',label:'Function text'},{key:'function',label:'Function'},{key:'location',label:'Location'},{key:'part',label:'Part number'},{key:'rating',label:'Rating'},{key:'x',label:'X',type:'number'},{key:'y',label:'Y',type:'number'},{key:'rotation',label:'Rotation',options:['0','90','180','270']},{key:'layer',label:'Layer'}];if(entity.symbol==='terminal')fields.unshift({key:'terminal',label:'Terminal no.'});}
else if(wire){title=wire.number?'Wire '+wire.number:'Connection';subtitle='Electrical connection';ic='wire';values=wire;fields=[{key:'number',label:'Wire number'},{key:'potential',label:'Potential'},{key:'crossSection',label:'Cross-section'},{key:'color',label:'Color',type:'color'},{key:'cable',label:'Cable tag'},{key:'core',label:'Core no.'},{key:'layer',label:'Layer'}];}
else if(annotation){title='Text';subtitle='Annotation';ic='text';values=annotation;fields=[{key:'text',label:'Text'},{key:'size',label:'Font size',type:'number'},{key:'x',type:'number'},{key:'y',type:'number'},{key:'color',label:'Color',type:'color'}];}
else{title=p.name;subtitle='Page '+(store.project.pages.indexOf(p)+1)+' · '+p.type;ic='page';values=p;fields=[{key:'name',label:'Description'},{key:'structure',label:'Structure'},{key:'type',label:'Page type',options:['schematic','cover','terminal','layout','overview']},{key:'width',label:'Width',type:'number'},{key:'height',label:'Height',type:'number'}];}
$('#inspector-body').innerHTML=`<div class="selection-summary"><div class="summary-icon">${icon(ic,23)}</div><div><strong>${h(title)}</strong><small>${h(subtitle)}</small></div></div><div class="section-heading">${selected.size>1?selected.size+' objects selected':'General'}</div><rf-property-grid></rf-property-grid>${entity?'<div class="section-heading">Cross-references</div><div id="crossrefs"></div>':'<div class="section-heading">Drawing information</div><p class="inspector-note">Select a device or connection to edit its properties.<br><br>'+p.entities.length+' devices · '+p.wires.length+' connections<br>Grid: 10 drawing units<br>Drawing: '+p.width+' × '+p.height+'</p>'}`;
if(entity)$('#inspector-body').insertAdjacentHTML('beforeend','<button class="inspector-advanced" data-action="electricalProperties">Electrical properties…</button>');
const grid=$('rf-property-grid');grid.data={values,fields};grid.onpropertychange=e=>{let {key,value}=e.detail;if(key==='rotation')value=Number(value);act('Edit '+key,pr=>{const pg=pr.pages.find(x=>x.id===p.id);const target=item?[...pg.entities,...pg.wires,...pg.annotations].find(x=>x.id===item.id):pg;target[key]=value;});};if(entity){const refs=crossReferences(store.project,entity);$('#crossrefs').innerHTML=refs.length?refs.map(r=>`<button class="crossref" data-goto="${r.entityId}"><span>${h(r.type)}</span><b>/${r.page}.${r.column}</b></button>`).join(''):'<p class="inspector-note">No related functions on other placements.</p>';}}
function renderBottom(){$$('[data-bottom]').forEach(b=>b.classList.toggle('active',b.dataset.bottom===bottom));$('#issue-count').textContent=issues.length;let rows=[];if(bottom==='messages')rows=issues.map(i=>({Severity:i.severity==='error'?'● Error':i.severity==='warning'?'△ Warning':'ⓘ Info',Code:i.code,Description:i.message,Page:store.project.pages.findIndex(p=>p.id===i.pageId)+1,_pageId:i.pageId,_entityId:i.entityId}));if(bottom==='connections')rows=connectionsReport(store.project);if(bottom==='parts')rows=bomReport(store.project);if(bottom==='activity')rows=activity.slice(0,60);if(bottom==='comments'){renderComments();return;}$('#bottom-content').innerHTML='<rf-data-table></rf-data-table>';const t=$('#bottom-content rf-data-table');t.data=rows;t.onrowselect=e=>{if(e.detail._entityId)goToEntity(e.detail._entityId,e.detail._pageId);};if(!rows.length)$('#bottom-content').innerHTML=`<div class="empty">${bottom==='messages'?'Run Check project to inspect electrical connections and device data.':'No records to show.'}</div>`;}
function renderAll(){if(!store.project.pages.some(p=>p.id===pageId))pageId=store.project.pages[0].id;$('#title').textContent=store.project.name+' · '+store.project.number;$('#project-stats').textContent=store.project.pages.length+' pages · '+store.project.pages.reduce((n,p)=>n+p.entities.length,0)+' devices';renderTabs();renderNavigator();renderInspector();renderBottom();renderer.selected=selected;renderer.setDocument(store.project,page());status();}
function status(){$('#zoom-label').textContent=Math.round(renderer.view.scale*100)+'%';$('#render-status').textContent=renderer.backend;$('#snap-status').textContent='SNAP '+(snapping?'ON':'OFF');$('#tool-status').textContent=tool==='place'?'Place '+getSymbol(placeSymbol).name:({select:'Selection',wire:'Connection',pan:'Pan',text:'Text'}[tool]||tool);}
function openPage(id){pageId=id;selected.clear();wirePoints=[];renderer.preview=null;renderAll();renderer.fit();status();}
function goToEntity(id,pid){const p=pid?store.project.pages.find(p=>p.id===pid):store.project.pages.find(p=>[...p.entities,...p.wires,...p.annotations].some(e=>e.id===id));if(!p)return;pageId=p.id;selected=new Set([id]);renderAll();const e=p.entities.find(e=>e.id===id);if(e){renderer.view.x=renderer.width/2-e.x*renderer.view.scale;renderer.view.y=renderer.height/2-e.y*renderer.view.scale;renderer.invalidate();}}
function setTool(t,symbol){tool=t;if(symbol)placeSymbol=symbol;wirePoints=[];renderer.preview=null;renderer.showPins=t==='wire';$('#viewport').className='tool-'+tool;$('#canvas-hint').textContent={select:'Select an object to edit · Scroll to zoom · Space + drag to pan',wire:'Click a pin to start · Click to add corners · Click a pin or press Enter to finish',pan:'Drag the drawing to pan · Scroll to zoom',place:'Click the sheet to place '+getSymbol(placeSymbol).name+' · Esc to finish',text:'Click the sheet to insert text'}[tool];$$('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));renderRibbon();renderNavigator();status();renderer.invalidate();}
function dialog(title,content,buttons=[]){$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=content;$('#dialog-footer').innerHTML=buttons.map((b,i)=>`<button class="btn ${b.primary?'primary':''} ${b.danger?'danger':''}" data-dialog-btn="${i}">${h(b.label)}</button>`).join('');buttons.forEach((b,i)=>$(`[data-dialog-btn="${i}"]`).onclick=async()=>{try{await b.run();}catch(e){toast(e.message);}});if(!$('#dialog').open)$('#dialog').showModal();}
const close=()=>$('#dialog').close();
function formDialog(title,fields,values,onSave){dialog(title,`<form id="editor-form" class="form-grid">${fields.map(f=>`<label class="${f.wide?'full-width':''}">${h(f.label||f.key)}${f.options?`<select name="${f.key}">${f.options.map(v=>`<option ${values[f.key]===v?'selected':''}>${h(v)}</option>`).join('')}</select>`:`<input name="${f.key}" type="${f.type||'text'}" value="${h(values[f.key]??'')}" ${f.required?'required':''}>`}</label>`).join('')}</form>`,[{label:'Cancel',run:close},{label:'Apply',primary:true,run:async()=>{const form=$('#editor-form');if(!form.reportValidity())return;const data=Object.fromEntries(new FormData(form));fields.filter(f=>f.type==='number').forEach(f=>data[f.key]=Number(data[f.key]));await onSave(data);close();}}]);$('#editor-form').onsubmit=e=>{e.preventDefault();$('[data-dialog-btn="1"]').click();};}
function confirmAction(title,message,run){dialog(title,`<p class="dialog-copy">${h(message)}</p>`,[{label:'Cancel',run:close},{label:'Continue',primary:true,run:()=>{run();close();}}]);}
function persistDraft(){try{preferences.setItem('relayforge-draft',JSON.stringify({project:store.project,revision:client.revision,savedAt:Date.now()}));}catch{toast('Local recovery storage is full. Export a project backup.');}}
store.addEventListener('change',e=>{renderAll();if(suppress)return;dirty=true;activity.unshift({Time:new Date().toLocaleTimeString(),Action:e.detail.label,Author:user.name});persistDraft();if(client.id)client.queue(store.project);else $('#save-status').textContent='Unsaved draft';});
client.addEventListener('status',e=>{const {state,message,revision,transport}=e.detail;const labels={saved:browserLocal?'Saved in this browser':'All changes saved',unsaved:'Unsaved changes',saving:'Saving…',offline:'Offline · draft preserved',error:'Save failed · draft preserved',conflict:'Resolve edit conflict',merging:'Merging changes…'};$('#save-status').textContent=labels[state]||state;$('#sync-status').textContent=state==='saved'?(transport||'Synced')+' · r'+revision:state==='conflict'?'Conflict':state==='offline'?'Offline':'Revision '+revision;if(state==='saved'){dirty=false;try{preferences.removeItem('relayforge-draft');}catch{}}if(message)toast(message);});client.addEventListener('presence',e=>{const n=e.detail.length;$('.share-button').innerHTML=icon('users',15)+'Collaborate'+(n>1?' · '+n:'');});renderer.addEventListener('backend',status);
function moveEntities(pg,ids,dx,dy){const moved=pg.entities.filter(e=>ids.has(e.id));const oldPins=moved.flatMap(getPins);moved.forEach(e=>{e.x+=dx;e.y+=dy;});for(const a of pg.annotations)if(ids.has(a.id)){a.x+=dx;a.y+=dy;}for(const w of pg.wires){if(ids.has(w.id)){w.points.forEach(p=>{p.x+=dx;p.y+=dy;});continue;}for(const i of [0,w.points.length-1]){const p=w.points[i];if(oldPins.some(pin=>Math.hypot(pin.x-p.x,pin.y-p.y)<.1)){const neighbor=w.points[i===0?1:i-1];const vertical=Math.abs(p.x-neighbor.x)<.1;p.x+=dx;p.y+=dy;if(w.points.length>2){if(vertical)neighbor.x=p.x;else neighbor.y=p.y;}}}}}
function copySelection(){const p=page();clipboard={entities:clone(p.entities.filter(e=>selected.has(e.id))),wires:clone(p.wires.filter(e=>selected.has(e.id))),annotations:clone(p.annotations.filter(e=>selected.has(e.id)))};return clipboard.entities.length+clipboard.wires.length+clipboard.annotations.length;}
function pasteSelection(data=clipboard,dx=30,dy=30){if(!data)return toast('Copy objects first.');const ids=[];act('Paste objects',pr=>{const pg=pr.pages.find(p=>p.id===pageId);for(const type of ['entities','wires','annotations'])for(const original of data[type]||[]){const e=clone(original);e.id=uid();ids.push(e.id);if(type==='entities'){e.tag=nextTag(pr,getSymbol(e.symbol).prefix);e.x+=dx;e.y+=dy;}else if(type==='annotations'){e.x+=dx;e.y+=dy;}else e.points.forEach(p=>{p.x+=dx;p.y+=dy;});pg[type].push(e);}});selected=new Set(ids);renderAll();}
function report(kind){const title={parts:'Parts list',connections:'Connection list',terminals:'Terminal strip report',plc:'PLC address list',devices:'Device list'}[kind];const rows={parts:bomReport,connections:connectionsReport,terminals:terminalReport,plc:plcReport,devices:p=>p.pages.flatMap((pg,i)=>pg.entities.map(e=>({tag:e.tag,function:e.function,location:e.location,type:getSymbol(e.symbol).name,part:e.part,page:i+1})))}[kind](store.project);dialog(title,`<p class="dialog-copy">${rows.length} records · Generated from ${h(store.project.name)}</p><rf-data-table id="report-table"></rf-data-table>`,[{label:'Close',run:close},{label:'Export CSV',primary:true,run:()=>download(safeName(store.project.number)+'-'+kind+'.csv',toCSV(rows),'text/csv')}]);$('#report-table').data=rows;}
Object.assign(actions,{
 select:()=>setTool('select'),wire:()=>setTool('wire'),pan:()=>setTool('pan'),text:()=>setTool('text'),symbols:()=>{nav='symbols';renderNavigator();setTool('place');},junction:()=>setTool('place','junction'),potential:()=>setTool('place','potential'),
 undo:()=>{if(editingAllowed&&!store.undo())toast('Nothing to undo.');},redo:()=>{if(editingAllowed&&!store.redo())toast('Nothing to redo.');},
 copy:()=>toast(copySelection()+' objects copied'),paste:()=>pasteSelection(),duplicate:()=>{if(copySelection())pasteSelection();else toast('Select an object to duplicate.');},
 delete:()=>{if(!selected.size)return toast('Select objects to delete.');act('Delete objects',p=>{const pg=p.pages.find(p=>p.id===pageId);for(const key of ['entities','wires','annotations'])pg[key]=pg[key].filter(e=>!selected.has(e.id));});selected.clear();renderAll();},
 rotate:()=>{if(!selected.size)return toast('Select devices to rotate.');act('Rotate devices',p=>p.pages.find(p=>p.id===pageId).entities.filter(e=>selected.has(e.id)).forEach(e=>e.rotation=((e.rotation||0)+90)%360));},
 align:()=>{const entities=page().entities.filter(e=>selected.has(e.id));if(entities.length<2)return toast('Select at least two devices.');const x=Math.min(...entities.map(e=>e.x));act('Align devices',p=>{const pg=p.pages.find(p=>p.id===pageId);for(const e of entities)moveEntities(pg,new Set([e.id]),x-e.x,0);});},
 fit:()=>{renderer.fit();status();},zoomIn:()=>{renderer.zoom(1.2);status();},zoomOut:()=>{renderer.zoom(1/1.2);status();},grid:()=>{renderer.grid=!renderer.grid;renderer.invalidate();toast('Grid '+(renderer.grid?'shown':'hidden'));},snap:()=>{snapping=!snapping;status();},pins:()=>{renderer.showPins=!renderer.showPins;renderer.invalidate();},
 toggleProperties:()=>{$('#inspector').style.display=$('#inspector').style.display==='none'?'flex':'none';},toggleNavigator:()=>{$('#navigator').style.display=$('#navigator').style.display==='none'?'flex':'none';},toggleBottom:()=>$('.bottom-panel').classList.toggle('collapsed'),
 theme:()=>{document.documentElement.classList.toggle('dark');preferences.setItem('relayforge-theme',document.documentElement.classList.contains('dark')?'dark':'light');renderer.invalidate();},
 deviceNav:()=>{nav='devices';renderNavigator();},findDevice:()=>{nav='devices';$('#navigator').style.display='flex';renderNavigator();$('#nav-filter').focus();},
 validate:()=>{issues=validateElectrical(store.project);bottom='messages';$('.bottom-panel').classList.remove('collapsed');renderBottom();toast(`${issues.filter(i=>i.severity==='error').length} errors · ${issues.filter(i=>i.severity==='warning').length} warnings · ${issues.filter(i=>i.severity==='info').length} informational`);},
 number:()=>{let count;act('Number connections',p=>{count=numberWires(p,101);});toast(count+' electrical nets numbered.');},
 newPage:()=>formDialog('New page',[{key:'name',label:'Page description',required:true,wide:true},{key:'type',label:'Page type',options:['schematic','cover','terminal','layout','overview']},{key:'structure',label:'Structure'}],{name:'New schematic',type:'schematic',structure:'=MAIN+CP1'},d=>{const p=createPage(d.name,d.type);p.structure=d.structure;act('Create page',pr=>pr.pages.push(p));openPage(p.id);}),
 duplicatePage:()=>{let id;act('Duplicate page',pr=>{const p=clone(page());p.id=uid();id=p.id;p.name+=' (copy)';for(const key of ['entities','wires','annotations'])p[key].forEach(e=>e.id=uid());pr.pages.push(p);});if(id)openPage(id);},
 deletePage:()=>{if(store.project.pages.length===1)return toast('A project must contain at least one page.');confirmAction('Delete page','Delete '+page().name+' and all its objects? You can undo this action.',()=>act('Delete page',p=>p.pages=p.pages.filter(pg=>pg.id!==pageId)));},
 pageSettings:()=>formDialog('Page properties',[{key:'name',label:'Description',wide:true,required:true},{key:'structure',label:'Structure'},{key:'type',label:'Page type',options:['schematic','cover','terminal','layout','overview']},{key:'width',label:'Width',type:'number'},{key:'height',label:'Height',type:'number'}],page(),d=>act('Page properties',p=>Object.assign(p.pages.find(pg=>pg.id===pageId),d))),
 projectSettings:()=>formDialog('Project properties',[{key:'name',label:'Project name',required:true,wide:true},{key:'number',label:'Project number'},{key:'revision',label:'Revision'},{key:'author',label:'Author'},{key:'description',label:'Description',wide:true}],store.project,d=>act('Project properties',p=>Object.assign(p,d))),
 export:()=>download(safeName(store.project.name)+'.relayforge',JSON.stringify(store.project,null,2)),exportSVG:()=>download(safeName(page().name)+'.svg',exportSVG(store.project,page()),'image/svg+xml'),import:()=>$('#file-input').click(),
 print:()=>{const html=`<!doctype html><html><head><title>${h(store.project.name)}</title><style>@page{size:A3 landscape;margin:0}body{margin:0}svg{width:100%;height:100vh;display:block;page-break-after:always}@media print{svg{height:100vh}}</style></head><body>${store.project.pages.map(p=>exportSVG(store.project,p)).join('')}</body></html>`;const blob=new Blob([html],{type:'text/html'}),url=URL.createObjectURL(blob),win=window.open(url,'_blank');if(win)win.onload=()=>{win.print();setTimeout(()=>URL.revokeObjectURL(url),60000);};else{URL.revokeObjectURL(url);toast('Allow a new tab to open the print layout.');}},
 parts:()=>report('parts'),connections:()=>report('connections'),terminals:()=>report('terminals'),plc:()=>report('plc'),devicesReport:()=>report('devices'),reports:()=>{activeTab='Reports';renderRibbon();report('parts');},
 save:saveProject,newProject:()=>formDialog('New project',[{key:'name',label:'Project name',required:true,wide:true},{key:'number',label:'Project number'}],{name:'New electrical project',number:'RF-001'},async d=>{const p=createProject(d.name);p.number=d.number;await createAndOpen(p);}),projects:showProjects,collaborate:showCollaborate,history:showHistory,
 saveMacro:()=>{if(!copySelection())return toast('Select devices and connections to save a macro.');formDialog('Save window macro',[{key:'name',label:'Macro name',required:true,wide:true}],{name:'New circuit'},d=>act('Save macro',p=>p.macros.push({id:uid(),name:d.name,...clone(clipboard)})));},
 macros:()=>{dialog('Window macros',store.project.macros.length?store.project.macros.map(m=>`<div class="project-card" data-macro="${m.id}">${icon('layers',24)}<div><strong>${h(m.name)}</strong><small>${m.entities.length} devices · ${m.wires.length} connections</small></div></div>`).join(''):'<p class="dialog-copy">Select a circuit, then use Insert → Save macro to reuse it in this project.</p>',[{label:'Close',run:close}]);$$('[data-macro]').forEach(b=>b.onclick=()=>{const macro=store.project.macros.find(m=>m.id===b.dataset.macro);pasteSelection(macro,40,40);close();});},
 commands:showCommands,help:()=>dialog('Keyboard shortcuts',`<rf-data-table id="shortcuts"></rf-data-table>`,[{label:'Close',run:close}])||($('#shortcuts').data=[{Key:'V',Action:'Select objects'},{Key:'W',Action:'Draw connections'},{Key:'P',Action:'Place selected symbol'},{Key:'T',Action:'Insert text'},{Key:'Space + drag / middle mouse',Action:'Pan drawing'},{Key:'Mouse wheel',Action:'Zoom at cursor'},{Key:'F',Action:'Fit page'},{Key:'R',Action:'Rotate selected devices'},{Key:'G',Action:'Show / hide grid'},{Key:'Shift + click / drag empty area',Action:'Multiple selection / selection box'},{Key:'Ctrl+C / V / D',Action:'Copy / paste / duplicate'},{Key:'Ctrl+Z / Ctrl+Shift+Z',Action:'Undo / redo'},{Key:'Ctrl+S',Action:'Save project'},{Key:'Delete',Action:'Delete selected objects'},{Key:'Escape',Action:'Cancel active tool'}]),
 about:()=>dialog('About RelayForge Electrical',`<p><strong>RelayForge Electrical 0.2.0</strong></p><p class="dialog-copy">An original browser electrical CAD workspace. Plain JavaScript engine, standalone web controls, WebGPU rendering with Canvas fallback, and revisioned project collaboration.</p><p class="dialog-copy">This release supports RelayForge JSON, SVG, CSV and browser print. Engineering tools include cabinet routing, calculation traces and PLC interchange subsets. Native operations require the Windows EPLAN companion. Certification and full vendor roundtrip qualification remain external requirements.</p><p class="dialog-copy">Renderer: ${renderer.backend}<br>Visible line segments: ${renderer.lineCount||0}<br>Last render submission: ${(renderer.frameMs||0).toFixed(2)} ms</p>`,[{label:'Close',run:close}]),
 account:()=>dialog('Your account',`<p><strong>${h(user.name)}</strong></p><p class="dialog-copy">${h(user.email||'Local development account')}<br>Project role: ${h(client.role)}<br>${browserLocal?'Projects are stored in this browser only, not uploaded. Export backups before clearing browser data.':'Project data is saved to the server. Unsaved changes have a local recovery draft.'}</p>`,[{label:'Close',run:close}])
});
async function saveProject(){if(!ready)return toast('Project storage is still opening.');if(!editingAllowed)return toast('This project is read-only.');try{if(!client.id){await createAndOpen(store.project);}else{client.queue(store.project);await client.save();}}catch(e){persistDraft();toast(e.message);}}
async function createAndOpen(p){if(client.id&&client.id!==p.id&&client.pending){await client.save();if(client.pending)throw Error('Resolve pending changes before creating or importing another project.');}await client.request('/projects',{method:'POST',body:JSON.stringify({project:p})});await loadProject(p.id);}
async function loadProject(id){const data=await client.open(id);editingAllowed=data.role!=='viewer';suppress=true;store.replace(data.project);suppress=false;pageId=store.project.pages[Math.min(1,store.project.pages.length-1)].id;selected.clear();dirty=false;openPage(pageId);client.status('saved');preferences.setItem('relayforge-last-project',id);comments=[];}
async function showProjects(){dialog('Projects','<p class="dialog-copy">Loading projects…</p>',[{label:'Import project',run:actions.import},{label:'New project',primary:true,run:actions.newProject}]);try{const projects=await client.request('/projects');$('#dialog-body').innerHTML=projects.length?projects.map(p=>`<div class="project-card" data-project="${p.id}">${icon('folder',27)}<div><strong>${h(p.name)}</strong><small>Revision ${p.revision} · ${new Date(p.updated_at).toLocaleString()} · ${h(p.role)}</small></div>${icon('chevron',17)}</div>`).join(''):'<p class="dialog-copy">Create your first project to begin.</p>';$$('[data-project]').forEach(el=>el.onclick=async()=>{try{if(dirty){await saveProject();if(client.pending)return toast('Save or export your pending changes before switching projects.');}await loadProject(el.dataset.project);close();}catch(e){toast(e.message);}});}catch(e){$('#dialog-body').textContent=e.message;}}
async function showCollaborate(){if(browserLocal)return dialog('Browser-local workspace','<p class="dialog-copy">This GitHub Pages demo stores projects, the latest 100 revisions and comments in this browser only. Other tabs in this browser receive saved edits automatically. No project is uploaded.</p><p class="dialog-copy">Multi-user invitations and remote collaboration require the included Node/SQLite server or an authenticated Worker deployment. Export project JSON for a portable backup. Clearing site data deletes local projects.</p>',[{label:'Export backup',run:actions.export},{label:'Close',primary:true,run:close}]);if(!client.id)return toast('Save the project before inviting collaborators.');dialog('Collaborate on this project',`<p class="dialog-copy">Share editing or viewing access with a project invitation. Recipients must also have access to this hosted site. Invitations expire after 24 hours.</p><div id="members">Loading members…</div><div class="form-grid" style="margin-top:20px"><label>Invitation role<select id="invite-role"><option value="editor">Editor</option><option value="viewer">Viewer</option></select></label><label>Current revision<input readonly value="${client.revision}"></label><label class="full-width">Invitation link<input id="invite-link" readonly placeholder="Create an invitation link"></label></div><p class="dialog-copy" style="margin-top:15px">Committed revisions arrive over a live event stream. Edits to different fields merge automatically. Conflicting values require review; pending operations survive reloads.</p>`,[{label:'Close',run:close},{label:'Create invitation',primary:true,run:async()=>{const result=await client.request('/projects/'+client.id+'/invite',{method:'POST',body:JSON.stringify({role:$('#invite-role').value})});const link=new URL('./',location.href).href+'?join='+encodeURIComponent(result.token);$('#invite-link').value=link;try{await navigator.clipboard.writeText(link);toast('Invitation link copied.');}catch{toast('Invitation created. Copy the link above.');}}}]);try{const members=await client.request('/projects/'+client.id+'/members');$('#members').innerHTML=members.map(m=>`<div class="project-card">${icon('user',22)}<div><strong>${h(m.name)}</strong><small>${h(m.role)}</small></div>${client.role==='owner'&&m.role!=='owner'?`<button class="btn danger" data-remove-member="${h(m.user_id)}">Remove</button>`:''}</div>`).join('');$$('[data-remove-member]').forEach(b=>b.onclick=async()=>{await client.request('/projects/'+client.id+'/members',{method:'DELETE',body:JSON.stringify({userId:b.dataset.removeMember})});showCollaborate();});}catch(e){$('#members').textContent=e.message;}}
async function showHistory(){if(!client.id)return toast('Save the project to record revisions.');dialog('Revision history','<p class="dialog-copy">Loading history…</p>',[{label:'Close',run:close}]);try{const rows=await client.request('/projects/'+client.id+'/history');$('#dialog-body').innerHTML='<p class="dialog-copy">Restoring creates a new revision. Existing history is preserved.</p>'+rows.map(r=>`<div class="project-card">${icon('history',23)}<div><strong>Revision ${r.revision}</strong><small>${new Date(r.created_at).toLocaleString()} · ${h(r.author)}</small></div><button class="btn" data-revision="${r.revision}">Restore</button></div>`).join('');$$('[data-revision]').forEach(b=>b.onclick=async()=>{try{const r=await client.request('/projects/'+client.id+'/history/'+b.dataset.revision);act('Restore revision '+b.dataset.revision,p=>{Object.assign(p,renewRestoredIdentities(p,clone(r.project)));});close();}catch(e){toast(e.message);}});}catch(e){$('#dialog-body').textContent=e.message;}}
function showConflict({local,remote,merged,conflicts}){dialog('Review concurrent edits',`<p class="dialog-copy">${conflicts.length} object changes overlap with another revision. Your local draft is preserved. Download a backup before choosing which version to keep.</p><rf-data-table id="conflict-table"></rf-data-table>`,[{label:'Download my draft',run:()=>download('relayforge-conflict-backup.relayforge',JSON.stringify(local,null,2))},{label:'Use server version',run:()=>{suppress=true;store.replace(remote);suppress=false;client.pending=null;client.conflicted=false;client.status('saved');close();}},{label:'Keep my conflicting edits',primary:true,run:async()=>{suppress=true;store.replace(merged);suppress=false;await client.resolve(merged);close();}}]);$('#conflict-table').data=conflicts.map(c=>({Object:c}));}
async function loadComments(){if(!client.id)return;try{comments=await client.request('/projects/'+client.id+'/comments');if(bottom==='comments')renderComments();}catch(e){toast(e.message);}}
function renderComments(){$('#bottom-content').innerHTML=`<div class="comment-form"><input id="comment-text" placeholder="Add a comment on this page…" aria-label="Comment"><button class="btn" id="post-comment">Post</button></div>${comments.length?comments.map(c=>`<div class="comment-item"><span class="avatar">${h(c.author.slice(0,2).toUpperCase())}</span><div style="flex:1"><small>${h(c.author)} · ${new Date(c.created_at).toLocaleString()} · ${c.resolved?'Resolved':'Open'}</small><p>${h(c.text)}</p></div><button class="btn" data-comment-goto="${h(c.entity_id)}" data-comment-page="${h(c.page_id)}">Go to</button>${editingAllowed?`<button class="btn" data-resolve-comment="${h(c.id)}" data-resolved="${c.resolved?0:1}">${c.resolved?'Reopen':'Resolve'}</button>`:''}</div>`).join(''):''}`;$('#post-comment').onclick=async()=>{if(!client.id)return toast('Save this project before adding comments.');const text=$('#comment-text').value;if(!text.trim())return;try{await client.request('/projects/'+client.id+'/comments',{method:'POST',body:JSON.stringify({text,pageId,entityId:[...selected][0]||''})});await loadComments();}catch(e){toast(e.message);}};$$('[data-resolve-comment]').forEach(b=>b.onclick=async()=>{await client.request('/projects/'+client.id+'/comments',{method:'PATCH',body:JSON.stringify({id:b.dataset.resolveComment,resolved:b.dataset.resolved==='1'})});loadComments();});$$('[data-comment-goto]').forEach(b=>b.onclick=()=>{if(b.dataset.commentGoto)goToEntity(b.dataset.commentGoto,b.dataset.commentPage);else openPage(b.dataset.commentPage);});}
function showCommands(){const commands=[['newProject','New project','Ctrl+N'],['projects','Open project',''],['save','Save project','Ctrl+S'],['newPage','Create page',''],['symbols','Place symbol','P'],['wire','Draw connection','W'],['text','Insert text','T'],['findDevice','Find device',''],['validate','Check electrical project',''],['number','Number connections',''],['parts','Generate parts list',''],['terminals','Generate terminal report',''],['plc','PLC address list',''],['export','Export project JSON',''],['exportSVG','Export page SVG',''],['print','Print project / PDF',''],['collaborate','Collaborate',''],['history','Revision history',''],['help','Keyboard shortcuts','?']];dialog('Find a command','<input id="command-filter" placeholder="Type a command…" style="width:100%"><div class="command-list" id="command-list"></div>',[]);const draw=()=>{$('#command-list').innerHTML=commands.filter(c=>c[1].toLowerCase().includes($('#command-filter').value.toLowerCase())).map(c=>`<button class="command-item" data-command="${c[0]}">${icon('chevron',14)}${c[1]}<kbd>${c[2]}</kbd></button>`).join('');$$('[data-command]').forEach(b=>b.onclick=()=>{close();actions[b.dataset.command]();});};$('#command-filter').oninput=draw;draw();$('#command-filter').focus();}
function screenPoint(e){const r=$('#viewport').getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top};}
function eventPoint(e){const world=renderer.screenToWorld(screenPoint(e));const near=page().entities.flatMap(getPins).find(p=>Math.hypot(world.x-p.x,world.y-p.y)<12/renderer.view.scale);return near?{x:near.x,y:near.y,pin:true}:{x:snapping?snap(world.x):world.x,y:snapping?snap(world.y):world.y};}
const viewport=$('#viewport');viewport.addEventListener('wheel',e=>{if(e.target.closest('button'))return;e.preventDefault();renderer.zoom(Math.exp(-e.deltaY*.0012),screenPoint(e));status();},{passive:false});
function routed(a,b){return a.x===b.x||a.y===b.y?[a,b]:[a,{x:a.x,y:b.y},b];}
function finishWire(){if(wirePoints.length<2){wirePoints=[];renderer.preview=null;renderer.invalidate();return;}const points=wirePoints.filter((p,i)=>!i||p.x!==wirePoints[i-1].x||p.y!==wirePoints[i-1].y).map(({x,y})=>({x,y}));if(points.length>1)act('Draw connection',pr=>pr.pages.find(p=>p.id===pageId).wires.push(createWire(points)));wirePoints=[];renderer.preview=null;renderer.invalidate();}
viewport.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;viewport.focus();const sp=screenPoint(e),p=eventPoint(e);if(space||e.button===1||tool==='pan'){e.preventDefault();drag={type:'pan',start:sp,view:clone(renderer.view)};viewport.setPointerCapture(e.pointerId);return;}if(e.button!==0)return;if(tool==='place'){act('Place '+getSymbol(placeSymbol).name,pr=>{const entity=createEntity(pr,placeSymbol,p.x,p.y);pr.pages.find(pg=>pg.id===pageId).entities.push(entity);selected=new Set([entity.id]);});return;}if(tool==='text'){formDialog('Insert text',[{key:'text',label:'Text',required:true,wide:true},{key:'size',label:'Font size',type:'number'}],{text:'Annotation',size:16},d=>act('Insert text',pr=>pr.pages.find(pg=>pg.id===pageId).annotations.push({id:uid(),...d,x:p.x,y:p.y})));return;}if(tool==='wire'){if(!wirePoints.length){wirePoints=[p];}else{wirePoints.push(...routed(wirePoints.at(-1),p).slice(1));if(p.pin)finishWire();}return;}
const hit=hitTest(page(),renderer.screenToWorld(sp),7/renderer.view.scale);if(hit){if(e.shiftKey){if(selected.has(hit.item.id))selected.delete(hit.item.id);else selected.add(hit.item.id);}else if(!selected.has(hit.item.id))selected=new Set([hit.item.id]);drag={type:'move',start:p,before:clone(page()),dx:0,dy:0};}else{if(!e.shiftKey)selected.clear();drag={type:'box',start:p,current:p,previous:new Set(selected)};}renderer.selected=selected;renderInspector();renderer.invalidate();viewport.setPointerCapture(e.pointerId);});
viewport.addEventListener('pointermove',e=>{const sp=screenPoint(e),p=eventPoint(e);$('#coords').innerHTML='X '+p.x.toFixed(1)+'&nbsp;&nbsp; Y '+p.y.toFixed(1);renderer.cursor=['place','wire','text'].includes(tool)?p:null;if(drag?.type==='pan'){renderer.view.x=drag.view.x+sp.x-drag.start.x;renderer.view.y=drag.view.y+sp.y-drag.start.y;renderer.invalidate();return;}if(drag?.type==='move'){drag.dx=p.x-drag.start.x;drag.dy=p.y-drag.start.y;const preview=clone(drag.before);moveEntities(preview,selected,drag.dx,drag.dy);renderer.setDocument(store.project,preview);return;}if(drag?.type==='box'){drag.current=p;renderer.preview={box:{x:Math.min(drag.start.x,p.x),y:Math.min(drag.start.y,p.y),w:Math.abs(p.x-drag.start.x),h:Math.abs(p.y-drag.start.y)}};}if(tool==='wire'&&wirePoints.length)renderer.preview={points:[...wirePoints,...routed(wirePoints.at(-1),p).slice(1)]};renderer.invalidate();});
viewport.addEventListener('pointerup',e=>{if(drag?.type==='move'&&(drag.dx||drag.dy)){const {dx,dy}=drag;act('Move selection',pr=>moveEntities(pr.pages.find(p=>p.id===pageId),selected,dx,dy));}if(drag?.type==='box'){const b=renderer.preview?.box;if(b){for(const e of [...page().entities,...page().annotations])if(e.x>=b.x&&e.x<=b.x+b.w&&e.y>=b.y&&e.y<=b.y+b.h)selected.add(e.id);for(const w of page().wires)if(w.points.every(p=>p.x>=b.x&&p.x<=b.x+b.w&&p.y>=b.y&&p.y<=b.y+b.h))selected.add(w.id);}renderer.preview=null;renderInspector();renderer.selected=selected;renderer.invalidate();}drag=null;if(viewport.hasPointerCapture(e.pointerId))viewport.releasePointerCapture(e.pointerId);});
viewport.addEventListener('pointercancel',()=>{drag=null;renderer.preview=null;renderer.setDocument(store.project,page());});viewport.addEventListener('pointerleave',()=>{renderer.cursor=null;renderer.invalidate();});viewport.addEventListener('dblclick',()=>{if(tool==='wire')finishWire();});viewport.addEventListener('contextmenu',e=>{e.preventDefault();setTool('select');});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(b){const action=actions[b.dataset.action];if(action)try{await action();}catch(error){toast(error.message);}return;}const tab=e.target.closest('[data-tab]');if(tab){if(tab.dataset.tab==='File')showProjects();else{activeTab=tab.dataset.tab;renderRibbon();}return;}const pg=e.target.closest('[data-page]');if(pg){openPage(pg.dataset.page);return;}const n=e.target.closest('[data-nav]');if(n){nav=n.dataset.nav;$('#nav-filter').value='';renderNavigator();return;}const s=e.target.closest('[data-symbol]');if(s){setTool('place',s.dataset.symbol);return;}const g=e.target.closest('[data-goto]');if(g){goToEntity(g.dataset.goto);return;}const bt=e.target.closest('[data-bottom]');if(bt){bottom=bt.dataset.bottom;$('.bottom-panel').classList.remove('collapsed');renderBottom();if(bottom==='comments')loadComments();}});
document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select')||$('#dialog').open)return;const mod=e.ctrlKey||e.metaKey;if(e.code==='Space'){e.preventDefault();space=true;}if(e.key==='Escape'){drag=null;selected.clear();setTool('select');renderAll();}if(mod){const m={s:'save',z:e.shiftKey?'redo':'undo',y:'redo',c:'copy',v:'paste',d:'duplicate',k:'commands'};if(e.key.toLowerCase()==='a'){e.preventDefault();selected=new Set([...page().entities,...page().wires,...page().annotations].map(e=>e.id));renderAll();}if(m[e.key.toLowerCase()]){e.preventDefault();actions[m[e.key.toLowerCase()]]();}return;}const m={v:'select',w:'wire',p:'symbols',t:'text',f:'fit',r:'rotate',g:'grid',Delete:'delete',Backspace:'delete','?':'help'};if(e.key==='Enter'&&tool==='wire')finishWire();else if(m[e.key]){e.preventDefault();actions[m[e.key]]();}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)&&selected.size){e.preventDefault();const n=e.shiftKey?10:snapping?10:1;act('Nudge objects',pr=>moveEntities(pr.pages.find(p=>p.id===pageId),selected,e.key==='ArrowLeft'?-n:e.key==='ArrowRight'?n:0,e.key==='ArrowUp'?-n:e.key==='ArrowDown'?n:0));}});document.addEventListener('keyup',e=>{if(e.code==='Space')space=false;});window.addEventListener('blur',()=>space=false);
$('#nav-filter').oninput=renderNavigator;$('#dialog-close').onclick=close;$('#dialog').addEventListener('click',e=>{if(e.target===$('#dialog'))close();});$('#theme').onclick=actions.theme;
$('#file-input').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{if(f.size>8_000_000)throw Error('Project exceeds the 8 MB limit.');const p=JSON.parse(await f.text());validateProject(p);p.id=uid();p.name+=' (import)';await createAndOpen(p);close();toast('Project imported.');}catch(error){toast('Import failed: '+error.message);}};
$$('.quick-access [data-action]').forEach(b=>b.innerHTML=icon(b.dataset.action,16));$('#theme').innerHTML=icon('moon',17);$('.command-search').innerHTML=icon('search',14)+'<span>Find a command</span><kbd>⌘ K</kbd>';$('.share-button').innerHTML=icon('users',15)+'Collaborate';$('#filter-icon').innerHTML=icon('search',13);$$('.panel-title [data-action],.canvas-actions [data-action],.navigator-foot [data-action]').forEach(b=>b.innerHTML=icon({newPage:'plus',fit:'fit',grid:'grid',toggleProperties:b.closest('.panel-title')?'close':'settings',projectSettings:'settings'}[b.dataset.action]||'settings',16));$('#floating-tools').innerHTML=[['select','Select · V','select'],['wire','Connect · W','wire'],['symbols','Place symbol · P','bolt'],['text','Text · T','text'],['pan','Pan · Space','pan']].map(([a,t,i])=>`<button data-action="${a}" data-tool="${a==='symbols'?'place':a}" title="${t}" aria-label="${t}">${icon(i,18)}</button>`).join('')+'<div class="tool-divider"></div>'+btn('rotate','','rotate','title="Rotate · R" aria-label="Rotate"')+btn('delete','','trash','title="Delete" aria-label="Delete"');
installAdvanced({actions,catalog,act,dialog,close,toast,download,formDialog,getProject:()=>store.project,getPage:page,getSelection:()=>selected,getRevision:()=>client.revision});
if(preferences.getItem('relayforge-theme')==='dark')document.documentElement.classList.add('dark');renderRibbon();renderAll();renderer.fit();setTool('select');
async function initialize(){const recoveryDraft=preferences.getItem('relayforge-draft');try{user=await client.request('/me');$('.avatar').textContent=user.name.split(/[\s@.]/).map(s=>s[0]).slice(0,2).join('').toUpperCase();const joining=new URLSearchParams(location.search).get('join');if(joining){const result=await client.request('/join',{method:'POST',body:JSON.stringify({token:joining})});history.replaceState(null,'',location.pathname);await loadProject(result.id);}else{const projects=await client.request('/projects');if(projects.length){const last=preferences.getItem('relayforge-last-project');await loadProject(projects.some(p=>p.id===last)?last:projects[0].id);}else await createAndOpen(store.project);}const draft=JSON.parse(recoveryDraft||'null');if(draft?.project){dialog('Recover unsaved changes','<p class="dialog-copy">A local recovery draft is available. Download it for safekeeping or recover it as a separate project.</p>',[{label:'Discard draft',run:()=>{preferences.removeItem('relayforge-draft');close();}},{label:'Download draft',run:()=>download('recovered-project.relayforge',JSON.stringify(draft.project,null,2))},{label:'Recover as project',primary:true,run:async()=>{const p=clone(draft.project);p.id=uid();p.name+=' (recovered)';await createAndOpen(p);preferences.removeItem('relayforge-draft');close();}}]);}ready=true;}catch(e){ready=true;$('#save-status').textContent='Storage unavailable · local draft';$('#sync-status').textContent='Not connected';toast(e.message+' — editing and export remain available.');}renderer.fit();status();}
initialize();
window.addEventListener('beforeunload',e=>{if(dirty||client.pending){persistDraft();e.preventDefault();e.returnValue='';}});
const context=document.modelContext;if(context?.registerTool){const lifecycle=new AbortController();const register=t=>Promise.resolve(context.registerTool(t,{signal:lifecycle.signal})).catch(()=>{});register({name:'read_electrical_project',description:'Read pages, devices and validation summary for the current electrical project.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({id:store.project.id,name:store.project.name,pages:store.project.pages.map(p=>({id:p.id,name:p.name,devices:p.entities.length})),issues:validateElectrical(store.project)})});register({name:'insert_electrical_symbols',description:'Create symbol placements on the current schematic page.',inputSchema:{type:'object',properties:{symbols:{type:'array',maxItems:100,items:{type:'object',properties:{symbol:{type:'string'},x:{type:'number'},y:{type:'number'}},required:['symbol','x','y'],additionalProperties:false}}},required:['symbols'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!editingAllowed)throw Error('Project is read-only');if(!Array.isArray(input.symbols)||input.symbols.length>100||input.symbols.some(s=>!getSymbol(s.symbol)||!Number.isFinite(s.x)||!Number.isFinite(s.y)))throw Error('Invalid symbols');store.transact('Insert symbols',pr=>{const pg=pr.pages.find(p=>p.id===pageId);input.symbols.forEach(s=>pg.entities.push(createEntity(pr,s.symbol,s.x,s.y)));});return {inserted:input.symbols.length,pageId};}});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
window.relayforge={get project(){return clone(store.project);},renderer,actions,version:'0.2.1'};
