import {validateProject} from '../packages/core/index.js';
import {diffProject} from '../packages/collaboration/operations.js';
import {commitOperations,operationStream} from './operations.js';
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
const fail=(message,status=400)=>Object.assign(Error(message),{status});
async function body(request){if(Number(request.headers.get('content-length'))>8_000_000)throw fail('Project is too large',413);const text=await request.text();if(text.length>8_000_000)throw fail('Project is too large',413);try{return JSON.parse(text);}catch{throw fail('Invalid JSON');}}
const stmt=(db,sql,...args)=>db.prepare(sql).bind(...args);
const hash=async text=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))).map(x=>x.toString(16).padStart(2,'0')).join('');
export async function api(request,env){try{const url=new URL(request.url),path=url.pathname.split('/').filter(Boolean).slice(1);const user=request.headers.get('oai-authenticated-user-id');if(!user)throw fail('Sign in is required to save or share projects',401);const email=request.headers.get('oai-authenticated-user-email')||'Engineer';let name=email;try{const raw=request.headers.get('oai-authenticated-user-full-name');if(raw)name=request.headers.get('oai-authenticated-user-full-name-encoding')==='percent-encoded-utf-8'?decodeURIComponent(raw):raw;}catch{}
if(request.method!=='GET'){const origin=request.headers.get('origin');if(origin&&origin!==url.origin)throw fail('Origin not allowed',403);}
const db=env.DB;if(!db)throw fail('Project database is unavailable',503);
if(path[0]==='me')return json({id:user,name,email});
if(path[0]==='join'&&request.method==='POST'){const b=await body(request);const invitation=await stmt(db,'SELECT * FROM invites WHERE token_hash = ? AND expires_at > ?',await hash(String(b.token||'')),Date.now()).first();if(!invitation)throw fail('Invitation is invalid or expired',404);await stmt(db,'INSERT INTO members(project_id,user_id,name,role) VALUES(?,?,?,?) ON CONFLICT(project_id,user_id) DO NOTHING',invitation.project_id,user,name,invitation.role).run();return json({id:invitation.project_id});}
if(path[0]!=='projects')throw fail('Not found',404);
if(!path[1]){if(request.method==='GET'){const rows=await stmt(db,'SELECT p.id,p.name,p.updated_at,p.revision,m.role FROM projects p JOIN members m ON m.project_id=p.id WHERE m.user_id=? ORDER BY p.updated_at DESC',user).all();return json(rows.results);}
if(request.method==='POST'){const b=await body(request);try{validateProject(b.project);}catch(e){throw fail(e.message);}if(new TextEncoder().encode(JSON.stringify(b.project)).length>1_800_000)throw fail('Project exceeds the 1.8 MB hosted snapshot limit',413);const id=b.project.id,now=Date.now();await db.batch([stmt(db,'INSERT INTO projects(id,name,document,revision,owner_id,updated_at) VALUES(?,?,?,1,?,?)',id,b.project.name,JSON.stringify(b.project),user,now),stmt(db,'INSERT INTO members(project_id,user_id,name,role) VALUES(?,?,?,?)',id,user,name,'owner'),stmt(db,'INSERT INTO revisions(project_id,revision,document,author,created_at) VALUES(?,1,?,?,?)',id,JSON.stringify(b.project),name,now)]);return json({id,revision:1},201);}throw fail('Method not allowed',405);}
const id=path[1];const member=await stmt(db,'SELECT role FROM members WHERE project_id=? AND user_id=?',id,user).first();if(!member)throw fail('Project not found or access denied',404);const writable=['owner','editor'].includes(member.role);if(request.method!=='GET'&&!writable)throw fail('This project is read-only',403);
if(path[2]==='operations'&&request.method==='POST'){const packet=await body(request);return json(await commitOperations(db,{projectId:id,user,name,packet}));}
if(path[2]==='events'&&request.method==='GET'){return operationStream(db,{projectId:id,user,name,since:Math.max(0,Number(url.searchParams.get('since'))||0),signal:request.signal});}
if(path[2]==='journal'&&request.method==='GET'){const since=Math.max(0,Number(url.searchParams.get('since'))||0);return json((await stmt(db,'SELECT operation_id,revision,changes,author,created_at FROM operations WHERE project_id=? AND revision>? ORDER BY revision LIMIT 200',id,since).all()).results.map(r=>({...r,changes:JSON.parse(r.changes)})));}
if(path[2]==='comments'){if(request.method==='GET')return json((await stmt(db,'SELECT * FROM comments WHERE project_id=? ORDER BY created_at',id).all()).results);if(request.method==='POST'){const b=await body(request);if(typeof b.text!=='string'||!b.text.trim()||b.text.length>4000)throw fail('Comment must be 1–4000 characters');await stmt(db,'INSERT INTO comments(id,project_id,page_id,entity_id,author,user_id,text,resolved,created_at) VALUES(?,?,?,?,?,?,?,0,?)',crypto.randomUUID(),id,b.pageId||'',b.entityId||'',name,user,b.text.trim(),Date.now()).run();return json({ok:true});}if(request.method==='PATCH'){const b=await body(request);await stmt(db,'UPDATE comments SET resolved=? WHERE id=? AND project_id=?',b.resolved?1:0,b.id,id).run();return json({ok:true});}}
if(path[2]==='members'){if(request.method==='GET')return json((await stmt(db,'SELECT user_id,name,role FROM members WHERE project_id=?',id).all()).results);if(member.role!=='owner')throw fail('Only the owner can manage access',403);if(request.method==='DELETE'){const b=await body(request);await db.batch([stmt(db,"DELETE FROM members WHERE project_id=? AND user_id=? AND role != 'owner'",id,b.userId),stmt(db,'DELETE FROM invites WHERE project_id=?',id)]);return json({ok:true});}}
if(path[2]==='invite'&&request.method==='POST'){if(member.role!=='owner')throw fail('Only the owner can create invitations',403);const b=await body(request),role=['editor','viewer'].includes(b.role)?b.role:'viewer';const token=crypto.randomUUID()+crypto.randomUUID();await stmt(db,'INSERT INTO invites(token_hash,project_id,role,expires_at) VALUES(?,?,?,?)',await hash(token),id,role,Date.now()+86400000).run();return json({token,expiresIn:86400,role});}
if(path[2]==='history'&&request.method==='GET'){if(path[3]){const r=await stmt(db,'SELECT document,revision FROM revisions WHERE project_id=? AND revision=?',id,Number(path[3])).first();if(!r)throw fail('Revision not found',404);return json({project:JSON.parse(r.document),revision:r.revision});}return json((await stmt(db,'SELECT revision,author,created_at FROM revisions WHERE project_id=? ORDER BY revision DESC LIMIT 100',id).all()).results);}
if(path.length>2)throw fail('Not found',404);
if(request.method==='GET'){const now=Date.now();await stmt(db,'INSERT INTO presence(project_id,user_id,name,last_seen) VALUES(?,?,?,?) ON CONFLICT(project_id,user_id) DO UPDATE SET name=excluded.name,last_seen=excluded.last_seen',id,user,name,now).run();const row=await stmt(db,'SELECT document,revision FROM projects WHERE id=?',id).first();const presence=(await stmt(db,'SELECT name,user_id FROM presence WHERE project_id=? AND last_seen>?',id,now-15000).all()).results;if(Number(url.searchParams.get('since'))===row.revision)return json({unchanged:true,revision:row.revision,presence});return json({project:JSON.parse(row.document),revision:row.revision,role:member.role,presence});}
if(request.method==='PUT'){const b=await body(request);try{validateProject(b.project);}catch(e){throw fail(e.message);}if(b.project.id!==id||!Number.isInteger(b.revision))throw fail('Project identity or revision is invalid');const current=await stmt(db,'SELECT document,revision FROM projects WHERE id=?',id).first();if(current.revision!==b.revision)return json({error:'Project changed on the server',project:JSON.parse(current.document),revision:current.revision},409);return json(await commitOperations(db,{projectId:id,user,name,packet:{operationId:crypto.randomUUID(),baseRevision:b.revision,changes:diffProject(JSON.parse(current.document),b.project)}}));}
throw fail('Method not allowed',405);
}catch(error){if(!error.status)console.error('RelayForge API:',error.message);return json({error:error.status?error.message:'The operation could not be completed. Export your draft or retry.',...(error.project?{project:error.project,revision:error.revision,conflicts:error.conflicts}: {})},error.status||500);}}
