export * from './symbols.js';
import {getPins,getSymbol,symbolBounds} from './symbols.js';
import './extended-symbols.js';
export const VERSION='0.2.0';
export const uid=()=>{if(globalThis.crypto.randomUUID)return globalThis.crypto.randomUUID();const b=globalThis.crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;const h=[...b].map(v=>v.toString(16).padStart(2,'0')).join('');return h.slice(0,8)+'-'+h.slice(8,12)+'-'+h.slice(12,16)+'-'+h.slice(16,20)+'-'+h.slice(20);};
export const clone=v=>structuredClone(v);
export const snap=(v,grid=10)=>Math.round(v/grid)*grid;
export function createProject(name='Untitled project'){return {schemaVersion:1,id:uid(),name,number:'RF-001',description:'',author:'Engineering',revision:'A',created:new Date().toISOString(),pages:[createPage('Power supply')],parts:[],macros:[],comments:[]};}
export function createPage(name='New schematic',type='schematic'){return {id:uid(),name,type,structure:'=MAIN+CP1',width:1200,height:800,entities:[],wires:[],annotations:[]};}
export function nextTag(project,prefix){const tags=project.pages.flatMap(p=>p.entities.map(e=>e.tag));let i=1;while(tags.includes('-'+prefix+i))i++;return '-'+prefix+i;}
export function createEntity(project,symbol,x,y,props={}){const def=getSymbol(symbol);if(!def)throw Error('Unknown symbol: '+symbol);return {id:uid(),symbol,x,y,rotation:0,tag:nextTag(project,def.prefix),label:'',part:def.part||'',location:'+CP1',function:'=MAIN',layer:'Devices',...props};}
export function createWire(points,props={}){if(points.length<2)throw Error('A wire needs at least two points');return {id:uid(),points:clone(points),number:'',color:'#253b50',crossSection:'1.5',potential:'',layer:'Connections',...props};}
export class ProjectStore extends EventTarget{
 constructor(project){super();validateProject(project);this.project=clone(project);this.undoStack=[];this.redoStack=[];}
 transact(label,fn){const before=clone(this.project);try{fn(this.project);validateProject(this.project);}catch(e){this.project=before;throw e;}this.undoStack.push({label,before,after:clone(this.project)});if(this.undoStack.length>100)this.undoStack.shift();this.redoStack=[];this.emit(label);}
 undo(){const c=this.undoStack.pop();if(c){this.redoStack.push(c);this.project=renewRestoredIdentities(this.project,clone(c.before));this.emit('Undo '+c.label);}return !!c;}
 redo(){const c=this.redoStack.pop();if(c){this.undoStack.push(c);this.project=renewRestoredIdentities(this.project,clone(c.after));this.emit('Redo '+c.label);}return !!c;}
 replace(project,{history=false}={}){validateProject(project);this.project=clone(project);if(!history){this.undoStack=[];this.redoStack=[];}this.emit('Load project');}
 emit(label){this.dispatchEvent(new CustomEvent('change',{detail:{label,project:this.project}}));}
}
export function validateProject(p){if(!p||p.schemaVersion!==1||typeof p.id!=='string'||typeof p.name!=='string'||!Array.isArray(p.pages)||p.pages.length<1||p.pages.length>500)throw Error('Invalid RelayForge project');let vertexCount=0;const coordinate=v=>Number.isFinite(v)&&Math.abs(v)<=100000;const ids=new Set();function id(v){if(typeof v!=='string'||ids.has(v))throw Error('Missing or duplicate object id');ids.add(v);}id(p.id);for(const page of p.pages){id(page.id);if(!Number.isFinite(page.width)||!Number.isFinite(page.height)||page.width<100||page.height<100||page.width>10000||page.height>10000)throw Error('Invalid sheet dimensions');if(!Array.isArray(page.entities)||!Array.isArray(page.wires)||!Array.isArray(page.annotations)||page.entities.length+page.wires.length>20000)throw Error('Invalid page objects');for(const e of page.entities){id(e.id);if(!getSymbol(e.symbol)||![e.x,e.y,e.rotation||0].every(coordinate))throw Error('Invalid device');}for(const w of page.wires){id(w.id);if(!Array.isArray(w.points)||w.points.length<2||w.points.length>1000||w.points.some(q=>!coordinate(q.x)||!coordinate(q.y)))throw Error('Invalid wire');vertexCount+=w.points.length;if(vertexCount>100000)throw Error('Project exceeds the 100,000 wire vertex limit');}for(const a of page.annotations){id(a.id);if(!coordinate(a.x)||!coordinate(a.y)||typeof a.text!=='string')throw Error('Invalid annotation');}}return p;}
export function distanceToSegment(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/(dx*dx+dy*dy||1)));return Math.hypot(p.x-a.x-t*dx,p.y-a.y-t*dy);}
export function hitTest(page,p,tolerance=12){for(const e of [...page.entities].reverse()){const b=symbolBounds(e);if(p.x>=b.x&&p.x<=b.x+b.w&&p.y>=b.y&&p.y<=b.y+b.h)return {type:'entity',item:e};}for(const a of [...page.annotations].reverse())if(Math.abs(a.x-p.x)<Math.max(35,a.text.length*5)&&Math.abs(a.y-p.y)<15)return {type:'annotation',item:a};for(const w of [...page.wires].reverse())for(let i=1;i<w.points.length;i++)if(distanceToSegment(p,w.points[i-1],w.points[i])<=tolerance)return {type:'wire',item:w};return null;}
// Graph joins endpoints and explicit junctions; unmarked crossing lines stay separate.
export function buildConnectivity(page){const nodes=[],parent=[];const add=(p,data)=>{nodes.push({...p,...data});parent.push(parent.length);return nodes.length-1;};const root=i=>parent[i]===i?i:(parent[i]=root(parent[i]));const join=(a,b)=>{parent[root(a)]=root(b);};const wireNodes=[];
for(const e of page.entities)for(const p of getPins(e))add(p,{type:'pin',entity:e,pin:p.id});
for(const w of page.wires){const indexes=w.points.map((p,i)=>add(p,{type:'wire',wire:w,index:i}));for(let i=1;i<indexes.length;i++)join(indexes[0],indexes[i]);wireNodes.push({w,indexes});}
const buckets=new Map();nodes.forEach((n,i)=>{if(n.type==='wire'&&n.index!==0&&n.index!==n.wire.points.length-1)return;const k=Math.round(n.x*100)+','+Math.round(n.y*100);if(buckets.has(k))join(i,buckets.get(k));else buckets.set(k,i);});
// Endpoint-to-segment joins support T junctions and device pins on a conductor.
const segmentGrid=new Map(),longSegments=[],cellSize=100;let cellCount=0;
for(const {w,indexes} of wireNodes)for(let i=1;i<w.points.length;i++){const a=w.points[i-1],b=w.points[i],segment={a,b,wireId:w.id,node:indexes[0]};if(![a.x,a.y,b.x,b.y].every(v=>Number.isFinite(v)&&Math.abs(v)<=100000))throw Error('Coordinates exceed graph limits');const cells=(Math.floor(Math.max(a.x,b.x)/cellSize)-Math.floor(Math.min(a.x,b.x)/cellSize)+1)*(Math.floor(Math.max(a.y,b.y)/cellSize)-Math.floor(Math.min(a.y,b.y)/cellSize)+1);if(cells>1024||cellCount+cells>200000){longSegments.push(segment);if(longSegments.length>2000)throw Error('Geometry exceeds graph processing limits');continue;}cellCount+=cells;for(let x=Math.floor(Math.min(a.x,b.x)/cellSize);x<=Math.floor(Math.max(a.x,b.x)/cellSize);x++)for(let y=Math.floor(Math.min(a.y,b.y)/cellSize);y<=Math.floor(Math.max(a.y,b.y)/cellSize);y++){const key=x+','+y;if(!segmentGrid.has(key))segmentGrid.set(key,[]);segmentGrid.get(key).push(segment);}}
for(let n=0;n<nodes.length;n++){const node=nodes[n];if(node.type==='wire'&&node.index!==0&&node.index!==node.wire.points.length-1)continue;for(const seg of [...(segmentGrid.get(Math.floor(node.x/cellSize)+','+Math.floor(node.y/cellSize))||[]),...longSegments]){if(node.wire?.id!==seg.wireId&&distanceToSegment(node,seg.a,seg.b)<0.01)join(n,seg.node);}}
const groups=new Map();nodes.forEach((n,i)=>{const key=root(i);if(!groups.has(key))groups.set(key,{id:`net-${key}`,pins:[],wires:[],potentials:[]});const g=groups.get(key);if(n.type==='pin')g.pins.push(n);else if(!g.wires.some(w=>w.id===n.wire.id))g.wires.push(n.wire);});
return [...groups.values()].map(g=>({...g,potentials:[...new Set([...g.wires.map(w=>w.potential),...g.pins.filter(p=>p.entity.symbol==='potential'||p.entity.symbol==='ground').map(p=>p.entity.symbol==='ground'?'PE':p.entity.label)].filter(Boolean))]}));}
export function validateElectrical(project){const issues=[];for(const page of project.pages){const nets=buildConnectivity(page);for(const net of nets){if(net.potentials.length>1)issues.push({severity:'error',code:'E101',pageId:page.id,entityId:net.wires[0]?.id,message:'Conflicting potentials: '+net.potentials.join(' / ')});for(const p of net.pins)if(net.pins.length===1&&net.wires.length===0&&p.entity.symbol!=='junction')issues.push({severity:'warning',code:'W201',pageId:page.id,entityId:p.entity.id,message:`${p.entity.tag}:${p.pin} is not connected`});if(net.wires.length&&net.pins.length<2)issues.push({severity:'warning',code:'W202',pageId:page.id,entityId:net.wires[0].id,message:'Connection has fewer than two device pins'});}
 const tags=new Map();for(const e of page.entities){if(!e.tag)issues.push({severity:'error',code:'E102',pageId:page.id,entityId:e.id,message:'Missing device tag'});const key=[e.function,e.location,e.tag,e.symbol,e.terminal||''].join('|');if(tags.has(key)&&!['terminal','junction','potential','contact_no','contact_nc','contactor'].includes(e.symbol))issues.push({severity:'warning',code:'W203',pageId:page.id,entityId:e.id,message:`Repeated function ${e.tag}; verify designation`});tags.set(key,e);if(!e.part&&!['junction','potential','ground'].includes(e.symbol))issues.push({severity:'info',code:'I301',pageId:page.id,entityId:e.id,message:`${e.tag}: no part assigned`});}}
return issues;}
export function formatEndpoint(entity,pin){return `${entity.tag}${entity.symbol.startsWith('terminal')?':'+(entity.terminal||'1'):''}:${pin}`;}
export function connectionsReport(project){return project.pages.flatMap((page,index)=>buildConnectivity(page).filter(n=>n.wires.length).map((n,i)=>({page:index+1,net:n.wires.find(w=>w.number)?.number||`${index+1}.${i+1}`,potential:n.potentials.join('/'),connections:n.pins.map(p=>formatEndpoint(p.entity,p.pin)).sort().join(' ↔ '),crossSection:n.wires[0]?.crossSection||'',conductors:n.wires.length})));}
export function bomReport(project){const parts=new Map();for(const p of project.pages)for(const e of p.entities){if(!e.part)continue;const key=e.part;if(!parts.has(key))parts.set(key,{part:key,description:getSymbol(e.symbol)?.name||e.symbol,quantity:0,devices:[],_seen:new Set()});const r=parts.get(key),device=[e.function,e.location,e.tag,e.symbol==='terminal'?e.terminal:''].join('|');if(!r._seen.has(device)){r.quantity++;r.devices.push(e.tag);r._seen.add(device);}}return [...parts.values()].map(({_seen,...r})=>({...r,devices:r.devices.join(', ')}));}
export function terminalReport(project){return project.pages.flatMap((p,i)=>{const nets=buildConnectivity(p);return p.entities.filter(e=>e.symbol==='terminal').map(e=>({strip:e.tag,terminal:e.terminal||'1',page:i+1,part:e.part,connections:nets.filter(n=>n.pins.some(x=>x.entity.id===e.id)).flatMap(n=>n.pins.filter(x=>x.entity.id!==e.id).map(x=>formatEndpoint(x.entity,x.pin))).join(', ')}));});}
export function plcReport(project){return project.pages.flatMap((p,i)=>p.entities.filter(e=>e.symbol==='plc').flatMap(e=>getPins(e).filter(n=>/[IQ]/.test(n.id)).map(n=>({device:e.tag,address:n.id,page:i+1,description:e.label,module:e.part}))));}
export function crossReferences(project,entity){return project.pages.flatMap((p,i)=>p.entities.filter(e=>e.id!==entity.id&&e.tag===entity.tag&&e.function===entity.function&&e.location===entity.location).map(e=>({pageId:p.id,entityId:e.id,page:i+1,column:Math.min(10,Math.max(1,Math.ceil(e.x/120))),type:getSymbol(e.symbol)?.name})));}
export function numberWires(project,start=1){let n=start;for(const p of project.pages)for(const net of buildConnectivity(p).filter(n=>n.wires.length)){for(const w of net.wires)w.number=String(n);n++;}return n-start;}
export function toCSV(rows){if(!rows.length)return '';const keys=Object.keys(rows[0]);const cell=v=>'"'+String(v??'').replaceAll('"','""')+'"';return [keys,...rows.map(r=>keys.map(k=>r[k]))].map(r=>r.map(cell).join(',')).join('\r\n');}
// Entity-granularity three-way merge. Concurrent edits to the same object are explicit conflicts.
export function mergeProjects(base,local,remote){const conflicts=[];const eq=(a,b)=>JSON.stringify(a)===JSON.stringify(b);function merge(b,l,r,path){if(eq(l,r))return clone(l);if(eq(b,l))return clone(r);if(eq(b,r))return clone(l);if(Array.isArray(b)&&Array.isArray(l)&&Array.isArray(r)&&[...b,...l,...r].every(v=>v&&typeof v.id==='string')){const map=a=>new Map(a.map(x=>[x.id,x]));const bm=map(b),lm=map(l),rm=map(r);return [...new Set([...rm.keys(),...lm.keys()])].map(id=>merge(bm.get(id),lm.get(id),rm.get(id),path+'/'+id)).filter(x=>x!==undefined);}if(b&&l&&r&&typeof b==='object'&&!Array.isArray(b)&&!path.match(/\/(entities|wires|annotations)\//)){const out={};for(const k of new Set([...Object.keys(b),...Object.keys(l),...Object.keys(r)])){const v=merge(b[k],l[k],r[k],path+'/'+k);if(v!==undefined)out[k]=v;}return out;}conflicts.push(path);return clone(l);}return {project:merge(base,local,remote,''),conflicts};}

export function renewRestoredIdentities(previous,next){const ids=new Set(),mapping=new Map();function collect(v,fn){if(!v||typeof v!=='object')return;if(typeof v.id==='string')fn(v.id);for(const x of Object.values(v))if(typeof x==='object')collect(x,fn);}collect(previous,id=>ids.add(id));collect(next,id=>{if(!ids.has(id)&&!mapping.has(id))mapping.set(id,uid());});function replace(v){if(!v||typeof v!=='object')return;for(const k of Object.keys(v)){if(typeof v[k]==='string'&&mapping.has(v[k]))v[k]=mapping.get(v[k]);else if(typeof v[k]==='object')replace(v[k]);}}replace(next);return next;}
