import {sqliteTable,text,integer,primaryKey,index} from 'drizzle-orm/sqlite-core';
export const projects=sqliteTable('projects',{id:text('id').primaryKey(),name:text('name').notNull(),document:text('document').notNull(),revision:integer('revision').notNull(),ownerId:text('owner_id').notNull(),updatedAt:integer('updated_at').notNull()});
export const members=sqliteTable('members',{projectId:text('project_id').notNull().references(()=>projects.id),userId:text('user_id').notNull(),name:text('name').notNull(),role:text('role').notNull()},t=>[primaryKey({columns:[t.projectId,t.userId]}),index('idx_members_user').on(t.userId)]);
export const revisions=sqliteTable('revisions',{projectId:text('project_id').notNull().references(()=>projects.id),revision:integer('revision').notNull(),document:text('document').notNull(),author:text('author').notNull(),createdAt:integer('created_at').notNull()},t=>[primaryKey({columns:[t.projectId,t.revision]})]);
export const comments=sqliteTable('comments',{id:text('id').primaryKey(),projectId:text('project_id').notNull().references(()=>projects.id),pageId:text('page_id').notNull(),entityId:text('entity_id').notNull(),author:text('author').notNull(),userId:text('user_id').notNull(),text:text('text').notNull(),resolved:integer('resolved').notNull(),createdAt:integer('created_at').notNull()},t=>[index('idx_comments_project').on(t.projectId,t.createdAt)]);
export const presence=sqliteTable('presence',{projectId:text('project_id').notNull().references(()=>projects.id),userId:text('user_id').notNull(),name:text('name').notNull(),lastSeen:integer('last_seen').notNull()},t=>[primaryKey({columns:[t.projectId,t.userId]})]);
export const invites=sqliteTable('invites',{tokenHash:text('token_hash').primaryKey(),projectId:text('project_id').notNull().references(()=>projects.id),role:text('role').notNull(),expiresAt:integer('expires_at').notNull()});

export const operations=sqliteTable('operations',{projectId:text('project_id').notNull().references(()=>projects.id),operationId:text('operation_id').notNull(),revision:integer('revision').notNull(),payloadHash:text('payload_hash').notNull(),changes:text('changes').notNull(),author:text('author').notNull(),createdAt:integer('created_at').notNull()},t=>[primaryKey({columns:[t.projectId,t.operationId]}),index('idx_operations_revision').on(t.projectId,t.revision)]);
export const tombstones=sqliteTable('tombstones',{projectId:text('project_id').notNull().references(()=>projects.id),objectKey:text('object_key').notNull(),revision:integer('revision').notNull()},t=>[primaryKey({columns:[t.projectId,t.objectKey]})]);
