import {spawn} from 'node:child_process';import {access,readFile,writeFile,mkdir} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';
export const nativeOperations={
 exportProject:{action:'export',type:'PXFPROJECT',required:['PROJECTNAME','EXPORTFILE'],defaults:{EXPORTMASTERDATA:'1',EXPORTCONNECTIONS:'1'},output:'EXPORTFILE'},
 importProject:{action:'import',type:'PXFPROJECT',required:['PROJECTNAME','IMPORTFILE']},
 backupProject:{action:'backup',type:'PROJECT',required:['PROJECTNAME','DESTINATIONPATH','ARCHIVENAME'],defaults:{BACKUPMETHOD:'BACKUP',AUTOCOPYREFDATA:'1',INCLEXTDOCS:'1',INCLIMAGES:'1'}},
 restoreProject:{action:'restore',type:'PROJECT',required:['ARCHIVENAME','PROJECTNAME'],defaults:{UNPACKPROJECT:'0'}},
 generateMacros:{action:'generatemacros',required:['PROJECTNAME','WINDOWMACRODIR','PAGEMACRODIR'],defaults:{OVERWRITE:'0'}},
 exportPLC:{action:'plcservice',type:'BUSDATAEXPORT',required:['PROJECTNAME','CONVERTERID','CONFIGURATIONPROJECT','DESTINATIONFILE'],defaults:{LANGUAGE:'en_US',OVERWRITE:'0'},output:'DESTINATIONFILE'},
 importPLC:{action:'plcservice',type:'BUSDATAIMPORT',required:['PROJECTNAME','CONVERTERID','SOURCEFILE'],defaults:{LANGUAGE:'en_US',IMPORTMATCH:'0'}}
};
export function buildNativeCommand(job){const spec=nativeOperations[job.operation];if(!spec)throw Error('Unsupported bridge operation');if(job.operation==='generateMacros'&&job.macroProjectConfirmed!==true)throw Error('Confirm the source is an EPLAN Macro project');const allowed=new Set([...spec.required,...Object.keys(spec.defaults||{})]);for(const key of Object.keys(job.parameters||{}))if(!allowed.has(key))throw Error('Unsupported parameter '+key);const params={...spec.defaults,...job.parameters};for(const key of spec.required)if(typeof params[key]!=='string'||!params[key].trim())throw Error('Missing '+key);for(const value of Object.values(params))if(/[\r\n\0]/.test(value))throw Error('Control characters are forbidden');const args=['/Variant:Electric P8','/NoLoadWorkspace','/Auto','/Quiet','/Frame:0',spec.action];if(spec.type)args.push('/TYPE:'+spec.type);for(const [k,v] of Object.entries(params))args.push('/'+k+':'+v);return {args,output:spec.output?params[spec.output]:null,operation:job.operation};}
export async function executeNativeJob(job,{executable=process.env.EPLAN_EXE,timeoutMS=120000}={}){if(process.platform!=='win32')throw Error('Native EPLAN execution requires Windows and an installed licensed EPLAN runtime');if(!executable)throw Error('Set EPLAN_EXE to the installed EPLAN.exe');await access(executable);const cmd=buildNativeCommand(job);return new Promise((resolve,reject)=>{const process=spawn(executable,cmd.args,{shell:false,windowsHide:true,stdio:['ignore','pipe','pipe']});let stdout='',stderr='';process.stdout.on('data',b=>stdout=(stdout+b).slice(-64000));process.stderr.on('data',b=>stderr=(stderr+b).slice(-64000));let killed=false;const timer=setTimeout(()=>{killed=true;process.kill();},timeoutMS);process.on('error',e=>{clearTimeout(timer);reject(e);});process.on('close',async code=>{clearTimeout(timer);if(killed)return reject(Error('EPLAN operation timed out'));if(code!==0)return reject(Error('EPLAN exited with '+code+': '+stderr));if(cmd.output)try{await access(cmd.output);}catch{return reject(Error('EPLAN did not create expected output '+cmd.output));}resolve({operation:job.operation,exitCode:code,stdout,stderr,output:cmd.output,warnings:job.operation==='restoreProject'?['EPLAN may upgrade the restored project to its running version.']:[]});});});}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){const file=process.argv.find((a,i)=>i>1&&!a.startsWith('--'));if(!file){console.error('Usage: node bridge/eplan-bridge.mjs job.json [--dry-run]');process.exitCode=1;}else try{const job=JSON.parse(await readFile(file,'utf8'));console.log(JSON.stringify(process.argv.includes('--dry-run')?buildNativeCommand(job):await executeNativeJob(job),null,2));}catch(e){console.error(e.message);process.exitCode=1;}}
