/** Depth-tested WebGPU cabinet meshes. No application dependency. */
export class CabinetGPU {
 constructor(canvas){this.canvas=canvas;}
 async initialize(){if(!navigator.gpu)return false;const adapter=await navigator.gpu.requestAdapter();if(!adapter)return false;this.adapterInfo=adapter.info;this.device=await adapter.requestDevice();this.context=this.canvas.getContext('webgpu');this.format=navigator.gpu.getPreferredCanvasFormat();this.context.configure({device:this.device,format:this.format,alphaMode:'premultiplied'});const shader=this.device.createShaderModule({code:`
struct Camera { viewport:vec4f, center:vec4f, rotation:vec4f };
@group(0) @binding(0) var<uniform> camera:Camera;
struct Vertex { @builtin(position) position:vec4f, @location(0) color:vec4f };
@vertex fn vertexMain(@location(0) p:vec3f,@location(1) color:vec4f)->Vertex {
 let v=p-camera.center.xyz; let u=v.x*camera.rotation.x+v.z*camera.rotation.y;
 let w=-v.x*camera.rotation.y+v.z*camera.rotation.x;
 let y=v.y*camera.rotation.z-w*camera.rotation.w;
 let depth=v.y*camera.rotation.w+w*camera.rotation.z;
 var out:Vertex; out.position=vec4f(u*camera.viewport.z*2.0/camera.viewport.x,-y*camera.viewport.z*2.0/camera.viewport.y,0.5-depth/(2.0*camera.viewport.w),1.0);out.color=color;return out;
}
@fragment fn fragmentMain(in:Vertex)->@location(0) vec4f {return in.color;}
`});const messages=await shader.getCompilationInfo();if(messages.messages.some(m=>m.type==='error'))throw Error(messages.messages.map(m=>m.message).join('\n'));this.pipeline=await this.device.createRenderPipelineAsync({layout:'auto',vertex:{module:shader,entryPoint:'vertexMain',buffers:[{arrayStride:28,attributes:[{shaderLocation:0,offset:0,format:'float32x3'},{shaderLocation:1,offset:12,format:'float32x4'}]}]},fragment:{module:shader,entryPoint:'fragmentMain',targets:[{format:this.format}]},primitive:{topology:'triangle-list',cullMode:'none'},depthStencil:{format:'depth24plus',depthWriteEnabled:true,depthCompare:'less'},multisample:{count:4}});this.uniform=this.device.createBuffer({size:48,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST});this.bind=this.device.createBindGroup({layout:this.pipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:this.uniform}}]});this.device.lost.then(info=>this.onLost?.(info));return true;}
 draw(c,objects,{width,height,scale,yaw,pitch,selected,dpr=1}){const data=[],faces=[[0,1,2,3],[4,7,6,5],[0,4,5,1],[3,2,6,7],[0,3,7,4],[1,5,6,2]],shades=[.65,.95,.75,.8,.7,1];const box=(e)=>{const color=e.id===selected?'#dc985b':e.color||'#6083a9';const rgb=[1,3,5].map(i=>(parseInt(color.slice(i,i+2),16)||90)/255);const points=[[0,0,0],[1,0,0],[1,1,0],[0,1,0],[0,0,1],[1,0,1],[1,1,1],[0,1,1]].map(([a,b,d])=>[e.x+a*e.width,e.y+b*e.height,e.z+d*e.depth]);faces.forEach((face,f)=>{for(const k of [0,1,2,0,2,3])data.push(...points[face[k]],...rgb.map(v=>v*shades[f]),1);});};objects.forEach(box);for(const route of c.routes||[])for(let i=1;i<route.points.length;i++){const a=route.points[i-1],b=route.points[i],r=Math.max(1,route.diameter/2||1.5);box({x:Math.min(a.x,b.x)-r,y:Math.min(a.y,b.y)-r,z:Math.min(a.z,b.z)-r,width:Math.abs(a.x-b.x)+r*2,height:Math.abs(a.y-b.y)+r*2,depth:Math.abs(a.z-b.z)+r*2,color:'#efa249'});}
 const packed=new Float32Array(data);if(!this.buffer||this.capacity<packed.byteLength){this.buffer?.destroy();this.capacity=Math.max(256,packed.byteLength*2);this.buffer=this.device.createBuffer({size:this.capacity,usage:GPUBufferUsage.VERTEX|GPUBufferUsage.COPY_DST});}this.device.queue.writeBuffer(this.buffer,0,packed);this.device.queue.writeBuffer(this.uniform,0,new Float32Array([width,height,scale,Math.hypot(c.width,c.height,c.depth),c.width/2,c.height/2,c.depth/2,0,Math.cos(yaw),Math.sin(yaw),Math.cos(pitch),Math.sin(pitch)]));const w=Math.max(1,Math.round(width*dpr)),h=Math.max(1,Math.round(height*dpr));if(this.canvas.width!==w||this.canvas.height!==h||!this.depth){this.canvas.width=w;this.canvas.height=h;this.depth?.destroy();this.msaa?.destroy();this.depth=this.device.createTexture({size:[w,h],sampleCount:4,format:'depth24plus',usage:GPUTextureUsage.RENDER_ATTACHMENT});this.msaa=this.device.createTexture({size:[w,h],sampleCount:4,format:this.format,usage:GPUTextureUsage.RENDER_ATTACHMENT});}const encoder=this.device.createCommandEncoder(),pass=encoder.beginRenderPass({colorAttachments:[{view:this.msaa.createView(),resolveTarget:this.context.getCurrentTexture().createView(),loadOp:'clear',storeOp:'discard',clearValue:{r:.094,g:.149,b:.216,a:1}}],depthStencilAttachment:{view:this.depth.createView(),depthLoadOp:'clear',depthStoreOp:'discard',depthClearValue:1}});pass.setPipeline(this.pipeline);pass.setBindGroup(0,this.bind);pass.setVertexBuffer(0,this.buffer);pass.draw(packed.length/7);pass.end();this.device.queue.submit([encoder.finish()]);}
 dispose(){this.depth?.destroy();this.msaa?.destroy();this.buffer?.destroy();this.uniform?.destroy();this.device?.destroy();}
}
