import {CabinetGPU} from './gpu.js';
const faces=[[0,1,2,3],[4,7,6,5],[0,4,5,1],[3,2,6,7],[0,3,7,4],[1,5,6,2]];
function corners(e){return [[0,0,0],[1,0,0],[1,1,0],[0,1,0],[0,0,1],[1,0,1],[1,1,1],[0,1,1]].map(([a,b,c])=>({x:e.x+a*e.width,y:e.y+b*e.height,z:e.z+c*e.depth}));}
export class CabinetRenderer extends EventTarget{constructor(host){super();this.host=host;host.style.position='relative';this.gpuCanvas=document.createElement('canvas');this.gpuCanvas.style.cssText='position:absolute;inset:0;width:100%;height:100%;pointer-events:none';host.append(this.gpuCanvas);this.yaw=-.45;this.pitch=.35;this.zoom=1;this.canvas=document.createElement('canvas');this.canvas.style.cssText='width:100%;height:100%;display:block;position:relative;touch-action:none';host.append(this.canvas);this.ctx=this.canvas.getContext('2d');this.observer=new ResizeObserver(()=>this.draw());this.observer.observe(host);let drag;this.canvas.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,yaw:this.yaw,pitch:this.pitch,moved:false};this.canvas.setPointerCapture(e.pointerId);};this.canvas.onpointermove=e=>{if(!drag)return;drag.moved||=Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>4;this.yaw=drag.yaw+(e.clientX-drag.x)*.005;this.pitch=Math.max(-1.1,Math.min(1.1,drag.pitch+(e.clientY-drag.y)*.005));this.draw();};this.canvas.onpointerup=e=>{if(drag&&!drag.moved){const r=this.canvas.getBoundingClientRect(),p={x:e.clientX-r.left,y:e.clientY-r.top};const hit=[...(this.hitAreas||[])].reverse().find(b=>p.x>=b.x&&p.x<=b.x+b.w&&p.y>=b.y&&p.y<=b.y+b.h);this.selected=hit?.id;this.dispatchEvent(new CustomEvent('select',{detail:{id:hit?.id}}));this.draw();}drag=null;};this.canvas.onwheel=e=>{e.preventDefault();this.zoom=Math.max(.4,Math.min(4,this.zoom*Math.exp(-e.deltaY*.001)));this.draw();};this.backend='Canvas 3D projection';this.gpu=new CabinetGPU(this.gpuCanvas);this.gpu.onLost=()=>{this.gpuReady=false;this.backend='Canvas 3D projection';this.gpuCanvas.style.display='none';this.draw();};this.gpu.initialize().then(ready=>{if(this.disposed)return;this.gpuReady=ready;if(ready){this.backend='WebGPU 3D';this.draw();}}).catch(()=>{this.gpuReady=false;});}
setCabinet(c){this.cabinet=c;this.draw();}
project(p){const c=this.cabinet;let x=p.x-c.width/2,y=p.y-c.height/2,z=p.z-c.depth/2;const u=x*Math.cos(this.yaw)+z*Math.sin(this.yaw),w=-x*Math.sin(this.yaw)+z*Math.cos(this.yaw);return {x:this.w/2+u*this.scale,y:this.h/2+(y*Math.cos(this.pitch)-w*Math.sin(this.pitch))*this.scale,depth:y*Math.sin(this.pitch)+w*Math.cos(this.pitch)};}
draw(){if(!this.cabinet)return;const c=this.cabinet,r=this.host.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);this.w=r.width;this.h=r.height;this.scale=Math.min((r.width-80)/(c.width+c.depth*.5),(r.height-50)/(c.height+c.depth*.5))*this.zoom;this.canvas.width=Math.max(1,r.width*d);this.canvas.height=Math.max(1,r.height*d);const ctx=this.ctx;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,r.width,r.height);if(!this.gpuReady){ctx.fillStyle='#182637';ctx.fillRect(0,0,r.width,r.height);}this.hitAreas=[];const polys=[];const objects=[{id:'backplate',tag:'',x:0,y:0,z:0,width:c.width,height:c.height,depth:8,color:'#42526a'},...(c.ducts||[]).map(e=>({...e,color:'#6c7480'})),...c.components];for(const e of objects){const ps=corners(e).map(p=>this.project(p));for(let i=0;i<faces.length;i++){const pts=faces[i].map(k=>ps[k]);polys.push({pts,e,shade:[.65,.95,.75,.8,.7,1][i],depth:pts.reduce((s,p)=>s+p.depth,0)/4});}if(e.id!=='backplate'){this.hitAreas.push({id:e.id,x:Math.min(...ps.map(p=>p.x)),y:Math.min(...ps.map(p=>p.y)),w:Math.max(...ps.map(p=>p.x))-Math.min(...ps.map(p=>p.x)),h:Math.max(...ps.map(p=>p.y))-Math.min(...ps.map(p=>p.y))});}}
if(this.gpuReady)this.gpu.draw(c,objects,{width:r.width,height:r.height,scale:this.scale,yaw:this.yaw,pitch:this.pitch,selected:this.selected,dpr:d});polys.sort((a,b)=>(a.e.id==='backplate'?-1:0)-(b.e.id==='backplate'?-1:0)||a.depth-b.depth);if(!this.gpuReady){for(const f of polys){const col=f.e.color||'#6083a9';const rgb=[1,3,5].map(i=>parseInt(col.slice(i,i+2),16)||90);ctx.fillStyle=`rgb(${rgb.map(v=>Math.round(v*f.shade)).join(',')})`;ctx.strokeStyle=f.e.id===this.selected?'#ffb465':'#13202e';ctx.lineWidth=f.e.id===this.selected?2:1;ctx.beginPath();f.pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fill();ctx.stroke();}for(const route of c.routes||[]){ctx.strokeStyle='#efa249';ctx.lineWidth=2;ctx.beginPath();route.points.forEach((p,i)=>{const q=this.project(p);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y);});ctx.stroke();}}ctx.textAlign='center';ctx.font='12px Arial';for(const e of c.components){const p=this.project({x:e.x+e.width/2,y:e.y+e.height/2,z:e.z+e.depth});ctx.fillStyle='#fff';ctx.fillText(e.tag,p.x,p.y);}
ctx.textAlign='left';ctx.fillStyle='#bdcadb';ctx.font='12px Arial';ctx.fillText(`${c.width} × ${c.height} × ${c.depth} mm · ${this.backend} · drag to orbit · wheel to zoom`,15,22);ctx.fillStyle='#e9a357';ctx.fillText('X',r.width-70,r.height-25);ctx.fillStyle='#9bcaa3';ctx.fillText('Y',r.width-45,r.height-25);ctx.fillStyle='#89b9e9';ctx.fillText('Z',r.width-20,r.height-25);}
dispose(){this.disposed=true;this.gpu.dispose();this.gpuCanvas.remove();this.observer.disconnect();this.canvas.remove();}}
