import {uid} from '../core/index.js';
export * from './properties.js';
export const CALCULATION_VERSION='1.0.0';
function positive(v,name,zero=false){v=Number(v);if(!Number.isFinite(v)||(zero?v<0:v<=0))throw Error(name+' must be '+(zero?'nonnegative':'positive'));return v;}
export function voltageDrop(input){const system=input.system||'three-phase';if(!['dc','single-phase','three-phase'].includes(system))throw Error('Unknown circuit system');const voltage=positive(input.voltage,'Voltage'),current=positive(input.current,'Current',true),length=positive(input.lengthM,'One-way length',true),section=positive(input.sectionMM2,'Conductor area'),temperature=Number(input.temperatureC??20);if(!Number.isFinite(temperature)||temperature< -50||temperature>250)throw Error('Temperature outside supported range');const material=input.material||'copper';if(!['copper','aluminium'].includes(material))throw Error('Unknown conductor material');const rho=material==='copper'?.017241:.028264,alpha=material==='copper'?.00393:.00403;const r20=input.resistanceOhmKM!==''&&input.resistanceOhmKM!=null?positive(input.resistanceOhmKM,'Resistance per km'):rho*1000/section;const resistance=r20*(1+alpha*(temperature-20));const reactance=positive(input.reactanceOhmKM??.08,'Reactance',true);const pf=system==='dc'?1:positive(input.powerFactor??.85,'Power factor',true);if(pf>1)throw Error('Power factor exceeds 1');const phaseFactor=system==='three-phase'?Math.sqrt(3):2;const drop=phaseFactor*current*length/1000*(resistance*pf+(system==='dc'?0:reactance*Math.sqrt(1-pf*pf)*(input.powerFactorMode==='leading'?-1:1)));const limit=positive(input.limitPercent??3,'Voltage drop limit');return {version:CALCULATION_VERSION,system,resistanceOhmKM:resistance,dropV:drop,dropPercent:drop/voltage*100,limitPercent:limit,passes:Math.abs(drop/voltage*100)<=limit,powerLossW:(system==='three-phase'?3:2)*current*current*resistance*length/1000,formula:system==='dc'?'ΔU = 2 I L Rθ':system==='three-phase'?'ΔU ≈ √3 I L (Rθ cosφ + X sinφ)':'ΔU ≈ 2 I L (Rθ cosφ + X sinφ)',assumptions:['One-way conductor length; R and X in Ω/km.','Balanced sinusoidal AC; approximate steady-state drop.','Resistance is user supplied or estimated from bulk resistivity, not a cable ampacity table.'],inputs:structuredClone(input)};}
export function adiabaticCheck(input){const current=positive(input.faultCurrentA,'Fault current'),time=positive(input.clearingTimeS,'Clearing time'),k=positive(input.k,'Material/insulation k'),section=positive(input.sectionMM2,'Conductor area');if(time>5)throw Error('Adiabatic screening is limited to clearing times up to 5 s');const required=current*Math.sqrt(time)/k;return {requiredSectionMM2:required,availableSectionMM2:section,withstandI2t:(k*section)**2,faultI2t:current**2*time,passes:section>=required,formula:'S ≥ I √t / k',assumptions:['k must match conductor, insulation, initial and final temperature.','Use protective-device let-through I²t where current limiting is relevant.','This check does not establish protective coordination or disconnection compliance.'],inputs:structuredClone(input)};}
export function ampacityCheck(input){const base=positive(input.referenceAmpacityA,'Reference ampacity'),ambient=positive(input.ambientFactor,'Ambient factor'),grouping=positive(input.groupingFactor,'Grouping factor'),other=positive(input.otherFactor??1,'Other factor'),load=positive(input.loadCurrentA,'Design current'),breaker=positive(input.protectiveRatingA,'Protective rating');const iz=base*ambient*grouping*other;const i2=input.conventionalTripA==null||input.conventionalTripA===''?null:positive(input.conventionalTripA,'Conventional trip current');return {correctedAmpacityA:iz,loadCurrentA:load,protectiveRatingA:breaker,currentCoordination:load<=breaker&&breaker<=iz,overloadCondition:i2===null?null:i2<=1.45*iz,passes:!(load<=breaker&&breaker<=iz)?false:i2===null?null:i2<=1.45*iz,status:!(load<=breaker&&breaker<=iz)?'fail':i2===null?'incomplete':i2<=1.45*iz?'pass':'fail',formula:'Iz = It × Ca × Cg × Cother; Ib ≤ In ≤ Iz; I2 ≤ 1.45 Iz',assumptions:['Reference ampacity and correction factors must come from applicable installation/manufacturer tables.','An omitted I2 leaves the conventional operating-current condition unassessed.'],inputs:structuredClone(input)};}
export function conduitFill({widthMM,heightMM,limitPercent=40,wires=[]}){const area=positive(widthMM,'Width')*positive(heightMM,'Height');if(limitPercent>100)throw Error('Fill limit cannot exceed 100%');for(const w of wires){if(w.diameterMM>Math.min(widthMM,heightMM))throw Error('Wire diameter exceeds the duct opening');if(!Number.isInteger(Number(w.quantity??1)))throw Error('Wire count must be an integer');}let used=0;for(const w of wires)used+=Math.PI*(positive(w.diameterMM,'Wire diameter')/2)**2*positive(w.quantity??1,'Wire count');return {availableAreaMM2:area,occupiedAreaMM2:used,fillPercent:used/area*100,limitPercent:positive(limitPercent,'Limit'),passes:used/area*100<=limitPercent,formula:'Fill = Σ(n π d²/4) / (width × height)',assumptions:['Geometric area screening; this is not a certification of code-specific duct or conduit fill.']};}
export function calculationReport(type,input){const methods={voltageDrop,adiabatic:adiabaticCheck,ampacity:ampacityCheck};if(!methods[type])throw Error('Unknown calculation');return {id:uid(),type,date:new Date().toISOString(),...methods[type](input)};}

export * from './networks.js';
