// Typed, extensible RelayForge electrical properties; identifiers are original.
export const propertyDefinitions=new Map();
export function defineProperty(def){if(!def.key||!['string','number','boolean','enum'].includes(def.type))throw Error('Invalid property definition');propertyDefinitions.set(def.key,Object.freeze({...def}));}
const properties=[
['conductive','Closed conductive path','boolean','Terminal'],['interruptionPoint','Interruption point','string','Electrical'],['potentialScope','Potential scope','enum','Electrical',['function','project']],['tag','Device tag','string','Identity'],['function','Function designation','string','Identity'],['location','Location designation','string','Identity'],['label','Function text','string','Identity'],['representation','Representation','enum','Identity',['multiline','singleline','overview','layout']],['isMain','Main function','boolean','Identity'],['deviceId','Physical device ID','string','Identity'],['functionDefinition','Function definition','string','Identity'],
['ratedVoltage','Rated voltage (V)','number','Electrical'],['ratedCurrent','Rated current (A)','number','Electrical'],['powerKW','Rated power (kW)','number','Electrical'],['frequency','Frequency (Hz)','number','Electrical'],['powerFactor','Power factor','number','Electrical'],['voltageType','Voltage type','enum','Electrical',['AC','DC']],['potential','Potential','string','Electrical'],['signalType','Signal type','enum','Electrical',['power','control','digital','analog','safety','data']],['protectionClass','Protection class','string','Electrical'],['ipRating','IP rating','string','Electrical'],['sccrKA','SCCR (kA)','number','Electrical'],
['terminal','Terminal designation','string','Terminal'],['level','Terminal level','number','Terminal'],['devicePosition','Device position','number','Terminal'],['terminalType','Terminal type','enum','Terminal',['feedthrough','disconnect','fuse','PE','distribution']],['jumperGroup','Jumper group','string','Terminal'],['internalPin','Internal connection','string','Terminal'],['externalPin','External connection','string','Terminal'],['sortCode','Sort code','number','Terminal'],
['plcAddress','PLC address','string','PLC'],['plcSymbol','PLC symbol','string','PLC'],['dataType','Data type','enum','PLC',['BOOL','BYTE','WORD','DWORD','INT','DINT','REAL','LREAL','STRING']],['rack','Rack','number','PLC'],['slot','Slot','number','PLC'],['channel','Channel','number','PLC'],['cpu','CPU designation','string','PLC'],['network','Network','string','PLC'],['station','Station','string','PLC'],
['part','Part number','string','Part'],['manufacturer','Manufacturer','string','Part'],['orderNumber','Order number','string','Part'],['description','Part description','string','Part'],['quantity','Quantity','number','Part'],['widthMM','Width (mm)','number','Mechanical'],['heightMM','Height (mm)','number','Mechanical'],['depthMM','Depth (mm)','number','Mechanical'],['clearanceMM','Clearance (mm)','number','Mechanical'],['weightKG','Weight (kg)','number','Mechanical'],['mounting','Mounting','enum','Mechanical',['DIN35','plate','door','free']],['dissipationW','Heat dissipation (W)','number','Mechanical']
];properties.forEach(([key,label,type,group,options])=>defineProperty({key,label,type,group,options}));
export function coerceProperty(key,value){const def=propertyDefinitions.get(key);if(!def)throw Error('Unknown property '+key);if(value===''||value==null)return undefined;if(def.type==='boolean'){if(![true,false,'true','false'].includes(value))throw Error(def.label+' must be true or false');return value===true||value==='true';}if(def.type==='number'){const n=Number(value);if(!Number.isFinite(n)||n<0)throw Error(def.label+' must be a finite nonnegative number');if(key==='powerFactor'&&n>1)throw Error('Power factor must be between 0 and 1');return n;}if(def.type==='enum'&&!def.options.includes(value))throw Error('Invalid '+def.label);return String(value);}
export function effectiveProperty(project,entity,key){if(entity[key]!==undefined&&entity[key]!=='')return {value:entity[key],source:'function'};if(['tag','function','location','isMain','representation','terminal','level','devicePosition','plcAddress','plcSymbol','channel','internalPin','externalPin','interruptionPoint','conductive'].includes(key))return {value:undefined,source:'unset'};const group=project.pages.flatMap(p=>p.entities).filter(e=>physicalDeviceKey(e)===physicalDeviceKey(entity));const main=group.find(e=>e.isMain===true);if(main&&main[key]!==undefined&&main[key]!=='')return {value:main[key],source:'main function'};const part=(project.parts||[]).find(p=>p.part===(entity.part||main?.part));if(part&&part[key]!==undefined)return {value:part[key],source:'part'};if(project.defaults?.[key]!==undefined)return {value:project.defaults[key],source:'project'};return {value:undefined,source:'unset'};}
export function physicalDeviceKey(e){return e.deviceId||[e.function||'',e.location||'',e.tag||''].join('|');}
export function terminalKey(e){return [physicalDeviceKey(e),e.devicePosition??e.terminal??'',e.level??1,e.representation||'multiline'].join('|');}
export function validateProperties(project){const issues=[];const devices=new Map(),terminals=new Map(),addresses=new Map();for(const page of project.pages)for(const e of page.entities){const issue=(code,message,severity='error')=>issues.push({severity,code,message,pageId:page.id,entityId:e.id});for(const [key,def] of propertyDefinitions)if(e[key]!==undefined&&e[key]!=='')try{coerceProperty(key,e[key]);}catch(err){issue('P401',err.message);}
 const key=physicalDeviceKey(e);if(!devices.has(key))devices.set(key,[]);devices.get(key).push({e,page});if(e.symbol.startsWith('terminal')){const t=terminalKey(e);if(terminals.has(t))issue('T401','Duplicate terminal device position and level');terminals.set(t,e);if(e.terminalType==='PE'&&e.potential&&e.potential!=='PE')issue('T402','PE terminal has a non-PE potential');}if(e.plcAddress){const a=[e.cpu||'',e.plcAddress,e.representation||'multiline'].join('|');if(addresses.has(a))issue('P402','Duplicate PLC address '+e.plcAddress);addresses.set(a,e);}}
for(const [key,list] of devices){const mains=list.filter(x=>x.e.isMain===true&&x.e.representation!=='layout');if(mains.length>1)for(const {e,page} of mains)issues.push({severity:'error',code:'D401',message:'More than one main function for '+e.tag,pageId:page.id,entityId:e.id});if(list.some(x=>x.e.isMain===false)&&!mains.length)issues.push({severity:'warning',code:'D402',message:'Auxiliary functions have no explicit main function: '+list[0].e.tag,pageId:list[0].page.id,entityId:list[0].e.id});}return issues;}
export function engineeringTerminalReport(project){return project.pages.flatMap((p,i)=>p.entities.filter(e=>e.symbol.startsWith('terminal')).map(e=>({strip:physicalDeviceKey(e),terminal:e.terminal||'',level:e.level??1,position:e.devicePosition??e.terminal??'',type:e.terminalType||'feedthrough',jumper:e.jumperGroup||'',internal:e.internalPin||'1',external:e.externalPin||'2',part:effectiveProperty(project,e,'part').value||'',page:i+1}))).sort((a,b)=>a.strip.localeCompare(b.strip)||String(a.position).localeCompare(String(b.position),undefined,{numeric:true})||a.level-b.level);}
