import {clone,mergeProjects} from '../core/index.js';
export class CollaborationClient extends EventTarget{
 constructor({baseURL='/api',onRemote,onConflict}={}){super();Object.assign(this,{baseURL,onRemote,onConflict,revision:0,base:null,pending:null,saving:false,polling:false,timer:null,role:'owner',epoch:0});}
 async request(path,options={}){const res=await fetch(this.baseURL+path,{...options,headers:{'Content-Type':'application/json',...options.headers}});const data=await res.json();if(!res.ok)throw Object.assign(Error(data.error||`Request failed (${res.status})`),{status:res.status,data});return data;}
 async open(id){this.stop();const epoch=this.epoch;const data=await this.request('/projects/'+id);if(epoch!==this.epoch)throw Error('Project opening was superseded');this.id=id;this.revision=data.revision;this.base=clone(data.project);this.role=data.role;this.pending=null;this.conflicted=false;this.timer=setInterval(()=>this.poll().catch(e=>this.status('offline',e.message)),4000);return data;}
 queue(project){this.pending=clone(project);clearTimeout(this.debounce);if(!this.conflicted)this.debounce=setTimeout(()=>this.save().catch(()=>{}),800);this.status(this.conflicted?'conflict':'unsaved');}
 async save(){if(this.saving||this.conflicted||!this.pending||!this.id)return;this.saving=true;const local=clone(this.pending),base=clone(this.base),epoch=this.epoch,id=this.id,revision=this.revision;this.status('saving');try{const result=await this.request('/projects/'+id,{method:'PUT',body:JSON.stringify({revision,project:local})});if(epoch!==this.epoch||id!==this.id)return;this.revision=result.revision;this.base=clone(local);if(JSON.stringify(this.pending)===JSON.stringify(local))this.pending=null;this.status(this.pending?'unsaved':'saved');}catch(e){if(epoch!==this.epoch||id!==this.id)return;if(e.status===409){const remote=e.data,current=this.pending||local;const merged=mergeProjects(base,current,remote.project);this.revision=remote.revision;this.base=clone(remote.project);this.pending=merged.project;if(merged.conflicts.length){this.conflicted=true;this.onConflict?.({local:clone(current),remote:clone(remote.project),merged:merged.project,conflicts:merged.conflicts});this.status('conflict');}else{this.onRemote?.(clone(merged.project));this.status('merging');}}else{this.status('error',e.message);throw e;}}finally{if(epoch===this.epoch){this.saving=false;if(this.pending&&!this.conflicted){clearTimeout(this.debounce);this.debounce=setTimeout(()=>this.save().catch(()=>{}),1500);}}}}
 async poll(){if(!this.id||this.saving||this.polling||this.conflicted)return;this.polling=true;const epoch=this.epoch,id=this.id,revision=this.revision;try{const d=await this.request('/projects/'+id+'?since='+revision);if(epoch!==this.epoch||id!==this.id||this.saving||revision!==this.revision||d.revision<this.revision)return;this.dispatchEvent(new CustomEvent('presence',{detail:d.presence||[]}));if(d.unchanged)return;if(this.pending){const local=clone(this.pending),m=mergeProjects(this.base,local,d.project);this.revision=d.revision;this.base=clone(d.project);this.pending=m.project;if(m.conflicts.length){this.conflicted=true;this.onConflict?.({local,remote:d.project,merged:m.project,conflicts:m.conflicts});this.status('conflict');return;}this.onRemote?.(clone(m.project));}else{this.revision=d.revision;this.base=clone(d.project);this.onRemote?.(clone(d.project));this.status('saved');}}finally{if(epoch===this.epoch)this.polling=false;}}
 resolve(project){this.conflicted=false;this.pending=clone(project);return this.save();}
 status(state,message=''){this.dispatchEvent(new CustomEvent('status',{detail:{state,message,revision:this.revision}}));}
 stop(){this.epoch++;clearInterval(this.timer);clearTimeout(this.debounce);this.timer=null;this.saving=false;this.polling=false;}
 dispose(){this.stop();}
}
