import {clone,uid} from '../core/index.js';
import {diffProject,mergeOperationProjects,pathLabel} from './operations.js';
export class LiveCollaborationClient extends EventTarget{
constructor({baseURL='/api',onRemote,onConflict}={}){super();Object.assign(this,{baseURL,onRemote,onConflict,revision:0,base:null,pending:null,saving:false,epoch:0,role:'owner',transport:'Disconnected'});}
async request(path,options={}){const r=await fetch(this.baseURL+path,{...options,headers:{'Content-Type':'application/json',...options.headers}});const d=await r.json();if(!r.ok)throw Object.assign(Error(d.error||'Request failed'),{status:r.status,data:d});return d;}
key(id=this.id){return 'relayforge-operation-outbox:'+(this.userId||'unresolved')+':'+id;}
persist(){if(typeof localStorage==='undefined'||!this.id)return;try{if(this.pending||this.packet)localStorage.setItem(this.key(),JSON.stringify({base:this.base,pending:this.pending,packet:this.packet,packetProject:this.packetProject,revision:this.revision}));else localStorage.removeItem(this.key());}catch{this.status('error','Operation recovery storage is full. Export a backup.');}}
async open(id){this.stop();const epoch=this.epoch;const me=await this.request('/me');if(epoch!==this.epoch)throw Error('Superseded project');this.userId=me.id;const d=await this.request('/projects/'+id);if(epoch!==this.epoch)throw Error('Superseded project');Object.assign(this,{id,revision:d.revision,base:clone(d.project),pending:null,packet:null,role:d.role,conflicted:false});let saved;try{saved=JSON.parse(localStorage.getItem(this.key())||'null');}catch{}if(saved?.pending&&saved?.packet&&saved?.packetProject){this.base=clone(saved.base);this.pending=clone(saved.pending);this.packet=saved.packet;this.packetProject=clone(saved.packetProject);this.revision=saved.revision;d.project=clone(saved.pending);setTimeout(()=>this.save().catch(()=>{}),0);}else if(saved?.pending){const m=mergeOperationProjects(saved.base,saved.pending,d.project);this.pending=m.project;if(m.conflicts.length){this.conflicted=true;setTimeout(()=>this.conflict(saved.pending,d.project,m),0);}else{this.packet=saved.packet;this.packetProject=saved.packetProject;d.project=clone(m.project);setTimeout(()=>this.save().catch(()=>{}),0);}}this.connect();return d;}
connect(){if(typeof EventSource==='undefined'||!this.id)return;this.stream?.close();const epoch=this.epoch;const stream=new EventSource(this.baseURL+'/projects/'+this.id+'/events?since='+this.revision);this.stream=stream;this.transport='Connecting';stream.addEventListener('ready',()=>{this.transport='SSE live';this.status(this.pending?'unsaved':'saved');});stream.addEventListener('presence',e=>this.dispatchEvent(new CustomEvent('presence',{detail:JSON.parse(e.data)})));stream.addEventListener('revision',e=>{const d=JSON.parse(e.data);if(d.revision>this.revision){this.refreshAfter=true;this.poll().catch(()=>{});}});stream.addEventListener('access-revoked',()=>{stream.close();this.role='viewer';this.status('error','Project access was revoked');});const reconnect=()=>{stream.close();if(epoch===this.epoch)this.reconnectTimer=setTimeout(()=>this.connect(),900);};stream.addEventListener('reconnect',reconnect);stream.onerror=()=>{this.transport='Reconnecting';this.status('offline','Live updates are reconnecting; pending operations are preserved.');reconnect();};}
queue(project){this.paused=false;this.pending=clone(project);this.persist();clearTimeout(this.debounce);if(!this.conflicted)this.debounce=setTimeout(()=>this.save().catch(()=>{}),250);this.status(this.conflicted?'conflict':'unsaved');}
async save(){if(this.saving||this.conflicted||this.paused||!this.pending||!this.id)return;const epoch=this.epoch;this.saving=true;const sent=clone(this.pending);this.status('saving');try{if(!this.packet){const changes=diffProject(this.base,sent);if(!changes.length){this.pending=null;this.persist();this.status('saved');return;}this.packet={operationId:uid(),baseRevision:this.revision,changes};this.packetProject=sent;this.persist();}const packet=this.packet,packetProject=this.packetProject||sent;const d=await this.request('/projects/'+this.id+'/operations',{method:'POST',body:JSON.stringify(packet)});if(epoch!==this.epoch)return;const remaining=this.pending&&JSON.stringify(this.pending)!==JSON.stringify(packetProject)?mergeOperationProjects(packetProject,this.pending,d.project):null;this.base=clone(d.project);this.revision=d.revision;this.packet=null;this.packetProject=null;this.pending=remaining?remaining.project:null;if(remaining?.conflicts.length){this.conflicted=true;this.conflict(this.pending,d.project,remaining);}else if(JSON.stringify(this.pending||d.project)!==JSON.stringify(sent))this.onRemote?.(clone(this.pending||d.project));this.persist();this.status(this.pending?'unsaved':'saved');}catch(e){if(epoch!==this.epoch)return;if(e.status===409&&e.data.project){const remote=e.data.project,m=mergeOperationProjects(this.base,this.pending||sent,remote);this.base=clone(remote);this.revision=e.data.revision;this.packet=null;this.packetProject=null;this.pending=m.project;if(m.conflicts.length||e.data.conflicts?.length){this.conflicted=true;this.conflict(this.pending,remote,{...m,conflicts:m.conflicts.length?m.conflicts:e.data.conflicts});}else this.onRemote?.(clone(m.project));this.persist();}else{if([400,401,403,404,413].includes(e.status))this.paused=true;this.status('error',e.message);throw e;}}finally{if(epoch===this.epoch){this.saving=false;if(this.pending&&!this.conflicted&&!this.paused)this.debounce=setTimeout(()=>this.save().catch(()=>{}),1000);else if(this.refreshAfter)this.poll().catch(()=>{});}}}
conflict(local,remote,m){this.status('conflict');this.onConflict?.({local:clone(local),remote:clone(remote),merged:m.project,conflicts:m.conflicts.map(p=>Array.isArray(p)?pathLabel(p):p)});}
async poll(){if(!this.id||this.saving||this.polling||this.conflicted)return;this.polling=true;const epoch=this.epoch,revision=this.revision;this.refreshAfter=false;try{const d=await this.request('/projects/'+this.id+'?since='+revision);if(epoch!==this.epoch||this.saving||this.revision!==revision)return;this.dispatchEvent(new CustomEvent('presence',{detail:d.presence||[]}));if(d.unchanged)return;const m=this.pending?mergeOperationProjects(this.base,this.pending,d.project):null;this.base=clone(d.project);this.revision=d.revision;if(m){this.pending=m.project;if(m.conflicts.length){this.conflicted=true;this.conflict(this.pending,d.project,m);}else this.onRemote?.(clone(m.project));}else this.onRemote?.(clone(d.project));this.persist();this.status(this.pending?'unsaved':'saved');}finally{if(epoch===this.epoch){this.polling=false;if(this.refreshAfter&&!this.saving&&!this.conflicted)queueMicrotask(()=>this.poll().catch(()=>{}));}}}
async resolve(project){this.conflicted=false;this.packet=null;this.pending=clone(project);this.persist();return this.save();}
status(state,message=''){if(state==='saved'&&!this.pending&&!this.packet)this.persist();this.dispatchEvent(new CustomEvent('status',{detail:{state,message,revision:this.revision,transport:this.transport}}));}
stop(){this.persist();this.epoch++;clearTimeout(this.debounce);clearTimeout(this.reconnectTimer);this.stream?.close();this.saving=false;this.polling=false;}
dispose(){this.stop();}}
