const forbidden=new Set(['__proto__','constructor','prototype']);const copy=v=>structuredClone(v);const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);const present=(exists,value)=>exists?{exists:true,value:copy(value)}:{exists:false};
function keyed(v){return Array.isArray(v)&&v.every(x=>x&&typeof x==='object'&&typeof x.id==='string');}
export function diffProject(before,after){const changes=[];function walk(a,b,path,ae=true,be=true){if(ae===be&&same(a,b))return;if(ae&&be&&keyed(a)&&keyed(b)){const commonA=a.filter(x=>b.some(y=>y.id===x.id)).map(x=>x.id),commonB=b.filter(x=>a.some(y=>y.id===x.id)).map(x=>x.id);if(!same(commonA,commonB)){changes.push({path,before:present(true,a),after:present(true,b)});return;}const am=new Map(a.map(v=>[v.id,v])),bm=new Map(b.map(v=>[v.id,v]));for(const id of new Set([...am.keys(),...bm.keys()]))walk(am.get(id),bm.get(id),[...path,{id}],am.has(id),bm.has(id));return;}if(ae&&be&&a&&b&&typeof a==='object'&&typeof b==='object'&&!Array.isArray(a)&&!Array.isArray(b)){for(const key of new Set([...Object.keys(a),...Object.keys(b)])){if(forbidden.has(key))throw Error('Unsafe property key');walk(a[key],b[key],[...path,key],Object.hasOwn(a,key),Object.hasOwn(b,key));}return;}changes.push({path,before:present(ae,a),after:present(be,b)});}walk(before,after,[]);if(changes.length>5000)throw Error('Change set exceeds 5000 fields');return changes;}
function locate(root,path){if(!Array.isArray(path)||!path.length||path.length>32)throw Error('Invalid operation path');let parent=root;for(const segment of path.slice(0,-1)){if(typeof segment==='string'){if(forbidden.has(segment)||!parent||!Object.hasOwn(parent,segment))return null;parent=parent[segment];}else if(segment&&typeof segment.id==='string'&&Array.isArray(parent)){parent=parent.find(x=>x?.id===segment.id);if(!parent)return null;}else throw Error('Invalid operation path segment');}const last=path.at(-1);if(typeof last==='string'){if(forbidden.has(last)||!parent||Array.isArray(parent))throw Error('Invalid property target');return {parent,key:last,exists:Object.hasOwn(parent,last),value:parent[last]};}if(last&&typeof last.id==='string'&&Array.isArray(parent)){const index=parent.findIndex(x=>x?.id===last.id);return {parent,key:index,exists:index>=0,value:parent[index],itemId:last.id};}throw Error('Invalid operation target');}
export function applyChanges(project,changes,{force=false}={}){if(!Array.isArray(changes)||changes.length>5000)throw Error('Invalid operation list');const result=copy(project),conflicts=[];for(const change of changes){if(!change.before||!change.after||typeof change.before.exists!=='boolean'||typeof change.after.exists!=='boolean')throw Error('Invalid change precondition');const target=locate(result,change.path);if(!target){conflicts.push(change.path);continue;}const current=present(target.exists,target.value);if(same(current,change.after))continue;if(!same(current,change.before)){conflicts.push(change.path);if(!force)continue;}if(target.itemId){if(change.after.exists){if(change.after.value?.id!==target.itemId)throw Error('Changed identity in collection');if(target.exists)target.parent[target.key]=copy(change.after.value);else target.parent.push(copy(change.after.value));}else if(target.exists)target.parent.splice(target.key,1);}else if(change.after.exists)target.parent[target.key]=copy(change.after.value);else delete target.parent[target.key];}return {project:result,conflicts};}
export function mergeOperationProjects(base,local,remote){return applyChanges(remote,diffProject(base,local),{force:true});}
export function pathLabel(path){return path.map(p=>typeof p==='string'?p:'@'+p.id).join('/');}
export function deletionKeys(changes){return changes.filter(c=>c.before.exists&&!c.after.exists&&typeof c.path.at(-1)==='object').map(c=>pathLabel(c.path));}
export function additionKeys(changes){return changes.filter(c=>!c.before.exists&&c.after.exists&&typeof c.path.at(-1)==='object').map(c=>pathLabel(c.path));}

export function documentIdentities(doc){const result=new Set();function visit(v){if(!v||typeof v!=='object')return;if(typeof v.id==='string')result.add(v.id);for(const x of Object.values(v))if(typeof x==='object')visit(x);}visit(doc);return result;}
