import {getSymbol,getPins,transformPoint} from '../core/symbols.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
export function pageScene(project,page){const lines=[],texts=[];const add=(x1,y1,x2,y2,color='#334657',width=1.2)=>lines.push({x1,y1,x2,y2,color,width});const label=(x,y,value,size=11,color='#334657',align='left')=>texts.push({x,y,value:String(value),size,color,align});const box=(x,y,w,h,color,width)=>{add(x,y,x+w,y,color,width);add(x+w,y,x+w,y+h,color,width);add(x+w,y+h,x,y+h,color,width);add(x,y+h,x,y,color,width);};
box(28,28,page.width-56,page.height-56,'#8c9ba8',1);for(let i=1;i<=10;i++){const x=28+(page.width-56)*(i-.5)/10;label(x,20,i,10,'#81909e','center');add(x+(page.width-56)/20,28,x+(page.width-56)/20,38,'#8c9ba8',.8);}
const by=page.height-100;add(28,by,page.width-28,by,'#8c9ba8',1);add(280,by,280,page.height-28,'#8c9ba8',1);add(790,by,790,page.height-28,'#8c9ba8',1);add(1000,by,1000,page.height-28,'#8c9ba8',1);label(46,by+27,'RELAYFORGE',18,'#253b50');label(46,by+49,'E L E C T R I C A L',9,'#7b8996');label(299,by+23,page.name,19);label(299,by+49,project.name+'  /  '+page.structure,11);label(808,by+22,'PROJECT   '+project.number,10);label(808,by+43,'REVISION   '+project.revision,10);label(1018,by+23,'SHEET  '+(project.pages.indexOf(page)+1)+' / '+project.pages.length,13);label(1018,by+45,'A3 · '+page.width+' × '+page.height,10);
for(const w of page.wires){for(let i=1;i<w.points.length;i++)add(w.points[i-1].x,w.points[i-1].y,w.points[i].x,w.points[i].y,w.color||'#334657',1.5);if(w.number){const a=w.points[0],b=w.points[1];label((a.x+b.x)/2+5,(a.y+b.y)/2-5,w.number,9,'#64838e');}if(w.potential)label(w.points[0].x-8,w.points[0].y-10,w.potential,11,'#536c85');}
for(const e of page.entities){const def=getSymbol(e.symbol);if(!def)continue;const tr=(x,y)=>transformPoint(x,y,e);const ln=(x,y,xx,yy)=>{const a=tr(x,y),b=tr(xx,yy);add(a.x,a.y,b.x,b.y,e.color||'#21364c',1.5);};for(const s of def.shapes){if(s.kind==='polyline')for(let i=2;i<s.points.length;i+=2)ln(s.points[i-2],s.points[i-1],s.points[i],s.points[i+1]);if(s.kind==='rect'){ln(s.x,s.y,s.x+s.w,s.y);ln(s.x+s.w,s.y,s.x+s.w,s.y+s.h);ln(s.x+s.w,s.y+s.h,s.x,s.y+s.h);ln(s.x,s.y+s.h,s.x,s.y);}if(s.kind==='circle'){for(let i=0;i<32;i++){const a=i*Math.PI/16,b=(i+1)*Math.PI/16;ln(s.x+Math.cos(a)*s.r,s.y+Math.sin(a)*s.r,s.x+Math.cos(b)*s.r,s.y+Math.sin(b)*s.r);}}if(s.kind==='text'){const p=tr(s.x,s.y);label(p.x,p.y,s.value,s.size,'#21364c','center');}}
 const left=e.symbol==='motor'?45:e.symbol==='plc'?58:26;label(e.x+left,e.y-5,e.tag+(e.symbol==='terminal'?':'+(e.terminal||'1'):''),12,'#1f456b');if(e.label)label(e.x+left,e.y+11,e.label,10,'#68798b');if(e.rating)label(e.x+left,e.y+25,e.rating,10,'#68798b');for(const p of getPins(e)){if(!['junction','potential','ground','terminal'].includes(e.symbol))label(p.x+6,p.y+(p.y<e.y?-3:10),p.id,8,'#7c8b99');}}
for(const a of page.annotations)label(a.x,a.y,a.text,a.size||16,a.color||'#536b82');return {lines,texts};}
export function exportSVG(project,page){const {lines,texts}=pageScene(project,page);return `<svg xmlns="http://www.w3.org/2000/svg" width="${page.width}" height="${page.height}" viewBox="0 0 ${page.width} ${page.height}"><rect width="100%" height="100%" fill="white"/>${lines.map(l=>`<line x1="${l.x1}" y1="${l.y1}" x2="${l.x2}" y2="${l.y2}" stroke="${esc(l.color)}" stroke-width="${l.width}"/>`).join('')}${texts.map(t=>`<text x="${t.x}" y="${t.y}" font-family="Arial,sans-serif" font-size="${t.size}" fill="${esc(t.color)}" text-anchor="${t.align==='center'?'middle':'start'}">${esc(t.value)}</text>`).join('')}</svg>`;}
function rgb(hex){const v=/^#[0-9a-f]{6}$/i.test(hex)?hex:'#334657';return [parseInt(v.slice(1,3),16)/255,parseInt(v.slice(3,5),16)/255,parseInt(v.slice(5,7),16)/255,1];}
export class SchematicRenderer extends EventTarget{
 constructor(host){super();this.host=host;this.view={x:35,y:30,scale:.8};this.selected=new Set();this.grid=true;this.showPins=false;this.backend='Canvas 2D';this.dirty=false;this.canvases=['background','gpu','overlay'].map(name=>{const c=document.createElement('canvas');c.className='rf-canvas '+name;c.style.cssText='position:absolute;inset:0;width:100%;height:100%;pointer-events:none';host.append(c);return c;});this.ctx=this.canvases[0].getContext('2d');this.overlay=this.canvases[2].getContext('2d');this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(host);this.resize();this.initGPU();}
 async initGPU(){try{if(!navigator.gpu)return;const adapter=await navigator.gpu.requestAdapter();if(!adapter)return;this.adapterInfo={vendor:adapter.info?.vendor,architecture:adapter.info?.architecture,device:adapter.info?.device,description:adapter.info?.description};this.device=await adapter.requestDevice();const ctx=this.canvases[1].getContext('webgpu');this.format=navigator.gpu.getPreferredCanvasFormat();ctx.configure({device:this.device,format:this.format,alphaMode:'premultiplied'});this.gpuContext=ctx;const shader=this.device.createShaderModule({code:`struct Uniforms { resolution:vec2f, translation:vec2f, scale:f32, pad:f32, pad2:vec2f }; @group(0) @binding(0) var<uniform> u:Uniforms; struct Output { @builtin(position) pos:vec4f, @location(0) color:vec4f }; @vertex fn vs(@builtin(vertex_index) vi:u32,@location(0) ends:vec4f,@location(1) color:vec4f,@location(2) width:f32)->Output{let a=ends.xy*u.scale+u.translation;let b=ends.zw*u.scale+u.translation;let d=b-a;let normal=normalize(vec2f(-d.y,d.x)+vec2f(0.000001))*max(0.75,width*u.scale)*0.5;var pts=array<vec2f,6>(a-normal,a+normal,b-normal,b-normal,a+normal,b+normal);var o:Output;o.pos=vec4f(pts[vi]/u.resolution*vec2f(2.0,-2.0)+vec2f(-1.0,1.0),0.0,1.0);o.color=color;return o;} @fragment fn fs(i:Output)->@location(0) vec4f{return i.color;}`});this.pipeline=this.device.createRenderPipeline({layout:'auto',vertex:{module:shader,entryPoint:'vs',buffers:[{arrayStride:36,stepMode:'instance',attributes:[{shaderLocation:0,offset:0,format:'float32x4'},{shaderLocation:1,offset:16,format:'float32x4'},{shaderLocation:2,offset:32,format:'float32'}]}]},fragment:{module:shader,entryPoint:'fs',targets:[{format:this.format,blend:{color:{srcFactor:'src-alpha',dstFactor:'one-minus-src-alpha'},alpha:{srcFactor:'one',dstFactor:'one-minus-src-alpha'}}}]},primitive:{topology:'triangle-list'},multisample:{count:4}});this.uniform=this.device.createBuffer({size:32,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST});this.bindGroup=this.device.createBindGroup({layout:this.pipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:this.uniform}}]});this.device.lost.then(()=>{this.backend='Canvas 2D';this.pipeline=null;this.canvases[1].style.display='none';this.invalidate();this.dispatchEvent(new Event('backend'));});this.backend='WebGPU';this.dispatchEvent(new Event('backend'));this.invalidate();}catch(error){this.backend='Canvas 2D';this.pipeline=null;this.canvases[1].style.display='none';this.dispatchEvent(new Event('backend'));}}
 resize(){const r=this.host.getBoundingClientRect();this.width=Math.max(1,r.width);this.height=Math.max(1,r.height);this.dpr=Math.min(devicePixelRatio||1,2);for(const c of this.canvases){c.width=Math.round(this.width*this.dpr);c.height=Math.round(this.height*this.dpr);}this.msaa?.destroy();this.msaa=null;this.invalidate();}
 setDocument(project,page){this.project=project;this.page=page;this.scene=pageScene(project,page);this.invalidate();}
 fit(){if(!this.page)return;this.view.scale=Math.min((this.width-70)/this.page.width,(this.height-55)/this.page.height);this.view.x=(this.width-this.page.width*this.view.scale)/2;this.view.y=(this.height-this.page.height*this.view.scale)/2;this.invalidate();}
 zoom(factor,p={x:this.width/2,y:this.height/2}){const world=this.screenToWorld(p);this.view.scale=Math.min(5,Math.max(.1,this.view.scale*factor));this.view.x=p.x-world.x*this.view.scale;this.view.y=p.y-world.y*this.view.scale;this.invalidate();}
 screenToWorld(p){return {x:(p.x-this.view.x)/this.view.scale,y:(p.y-this.view.y)/this.view.scale};}
 worldToScreen(p){return {x:p.x*this.view.scale+this.view.x,y:p.y*this.view.scale+this.view.y};}
 invalidate(){if(this.dirty)return;this.dirty=true;requestAnimationFrame(()=>{this.dirty=false;this.render();});}
 render(){if(!this.scene)return;const start=performance.now(),c=this.ctx,o=this.overlay,{scale:s,x,y}=this.view,d=this.dpr;for(const ctx of [c,o]){ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,this.width,this.height);}c.fillStyle=getComputedStyle(this.host).getPropertyValue('--canvas-bg').trim()||'#dce2e8';c.fillRect(0,0,this.width,this.height);c.save();c.translate(x,y);c.scale(s,s);c.shadowColor='#17283922';c.shadowBlur=18;c.shadowOffsetY=4;c.fillStyle='#fff';c.fillRect(0,0,this.page.width,this.page.height);c.shadowBlur=0;c.shadowOffsetY=0;if(this.grid&&s>.35){c.fillStyle='#d5dfe8';for(let gx=40;gx<this.page.width-35;gx+=20)for(let gy=40;gy<this.page.height-110;gy+=20)c.fillRect(gx,gy,.8/s,.8/s);}
const lines=this.scene.lines.filter(l=>Math.max(l.x1,l.x2)*s+x>=-3&&Math.min(l.x1,l.x2)*s+x<=this.width+3&&Math.max(l.y1,l.y2)*s+y>=-3&&Math.min(l.y1,l.y2)*s+y<=this.height+3);
if(this.pipeline){try{this.drawGPU(lines);}catch{this.pipeline=null;this.backend='Canvas 2D';this.canvases[1].style.display='none';this.invalidate();}}if(!this.pipeline){for(const l of lines){c.beginPath();c.strokeStyle=l.color;c.lineWidth=l.width;c.moveTo(l.x1,l.y1);c.lineTo(l.x2,l.y2);c.stroke();}}c.restore();o.save();o.translate(x,y);o.scale(s,s);for(const t of this.scene.texts){o.font=`${t.size>=16?500:400} ${t.size}px Arial,sans-serif`;o.textAlign=t.align;o.fillStyle=t.color;o.fillText(t.value,t.x,t.y);}for(const e of this.page.entities){if(this.selected.has(e.id)){o.fillStyle='#eb7b171c';o.strokeStyle='#ec821c';o.lineWidth=1.5/s;const size=e.symbol==='plc'?80:46;o.fillRect(e.x-size,e.y-size,size*2,size*2);o.strokeRect(e.x-size,e.y-size,size*2,size*2);for(const [dx,dy] of [[-size,-size],[size,-size],[size,size],[-size,size]]){o.fillStyle='#fff';o.fillRect(e.x+dx-3/s,e.y+dy-3/s,6/s,6/s);o.strokeRect(e.x+dx-3/s,e.y+dy-3/s,6/s,6/s);}}if(this.showPins||this.selected.has(e.id))for(const p of getPins(e)){o.fillStyle='#f0a034';o.fillRect(p.x-2/s,p.y-2/s,4/s,4/s);}}
for(const w of this.page.wires)if(this.selected.has(w.id)){o.strokeStyle='#ef8a25';o.lineWidth=3/s;o.beginPath();w.points.forEach((p,i)=>i?o.lineTo(p.x,p.y):o.moveTo(p.x,p.y));o.stroke();}for(const a of this.page.annotations)if(this.selected.has(a.id)){o.strokeStyle='#ed8123';o.strokeRect(a.x-3,a.y-(a.size||16),a.text.length*(a.size||16)*.65,(a.size||16)+5);}
if(this.preview?.points){o.strokeStyle='#e78527';o.lineWidth=1.8/s;o.setLineDash([5/s,4/s]);o.beginPath();this.preview.points.forEach((p,i)=>i?o.lineTo(p.x,p.y):o.moveTo(p.x,p.y));o.stroke();o.setLineDash([]);}if(this.preview?.box){const b=this.preview.box;o.fillStyle='#2a80d61a';o.fillRect(b.x,b.y,b.w,b.h);o.strokeStyle='#2a80d6';o.lineWidth=1/s;o.strokeRect(b.x,b.y,b.w,b.h);}if(this.cursor){o.strokeStyle='#f18c39';o.lineWidth=1/s;o.beginPath();o.moveTo(this.cursor.x-8/s,this.cursor.y);o.lineTo(this.cursor.x+8/s,this.cursor.y);o.moveTo(this.cursor.x,this.cursor.y-8/s);o.lineTo(this.cursor.x,this.cursor.y+8/s);o.stroke();}o.restore();this.frameMs=performance.now()-start;this.lineCount=lines.length;}
 drawGPU(lines){const data=new Float32Array(lines.length*9);lines.forEach((l,i)=>data.set([l.x1,l.y1,l.x2,l.y2,...rgb(l.color),l.width],i*9));if(!this.vertexBuffer||this.bufferSize<data.byteLength){this.vertexBuffer?.destroy();this.bufferSize=Math.max(256,data.byteLength*2);this.vertexBuffer=this.device.createBuffer({size:this.bufferSize,usage:GPUBufferUsage.VERTEX|GPUBufferUsage.COPY_DST});}this.device.queue.writeBuffer(this.vertexBuffer,0,data);this.device.queue.writeBuffer(this.uniform,0,new Float32Array([this.width,this.height,this.view.x,this.view.y,this.view.scale,0,0,0]));if(!this.msaa)this.msaa=this.device.createTexture({size:[this.canvases[1].width,this.canvases[1].height],sampleCount:4,format:this.format,usage:GPUTextureUsage.RENDER_ATTACHMENT});const encoder=this.device.createCommandEncoder();const pass=encoder.beginRenderPass({colorAttachments:[{view:this.msaa.createView(),resolveTarget:this.gpuContext.getCurrentTexture().createView(),clearValue:{r:0,g:0,b:0,a:0},loadOp:'clear',storeOp:'discard'}]});pass.setPipeline(this.pipeline);pass.setBindGroup(0,this.bindGroup);pass.setVertexBuffer(0,this.vertexBuffer);pass.draw(6,lines.length);pass.end();this.device.queue.submit([encoder.finish()]);}
 dispose(){this.resizeObserver.disconnect();this.vertexBuffer?.destroy();this.uniform?.destroy();this.msaa?.destroy();this.device?.destroy();this.canvases.forEach(c=>c.remove());}
}
